"""Status-code smoke tests for every public route.

Catches the routine "did I break the URL routing or break a template
unrelated to my actual change" regression with one cheap test per
endpoint. Runs against the seeded test DB (alpha + beta inboxes
with a few articles) set up by tests/conftest.py.
"""
import pytest


def _clear_sitemap_cache():
    """Sitemap routes cache their XML in the `cache` table; cross-test
    mutations (e.g. flipping `art3.canonical_inbox_id`) won't be
    visible until the cached rows expire. Tests that need a fresh
    render call this first."""
    from sqlalchemy import delete
    from mimir.extensions import SessionLocal
    from mimir.models import CacheEntry
    with SessionLocal() as s:
        s.execute(delete(CacheEntry))
        s.commit()


# Endpoints that don't depend on a configured inbox.
def test_meta_index(client):
    assert client.get("/").status_code == 200


def test_footer_includes_mimir_version(client):
    from mimir import __version__
    body = client.get("/").data.decode()
    assert f"Generated by mimir {__version__}." in body


def test_meta_index_pins_inbox_first(client, monkeypatch):
    """Seeded fixtures have alpha + beta. Without a pin, alpha shows
    first (alphabetical). Pinning beta surfaces it ahead of alpha."""
    from mimir.config import settings

    monkeypatch.setattr(settings, "pinned_inboxes", [])
    body = client.get("/").data.decode()
    assert body.find("/alpha/") < body.find("/beta/")

    monkeypatch.setattr(settings, "pinned_inboxes", ["beta"])
    body = client.get("/").data.decode()
    assert body.find("/beta/") < body.find("/alpha/")


def test_healthz(client):
    r = client.get("/healthz")
    assert r.status_code == 200
    assert r.headers.get("Cache-Control") == "no-store"


def test_readyz(client):
    assert client.get("/readyz").status_code == 200


def test_unknown_inbox_404(client):
    assert client.get("/nonexistent/").status_code == 404
    assert client.get("/nonexistent/today").status_code == 404
    assert client.get("/nonexistent/2024/").status_code == 404
    assert client.get("/nonexistent/2024/05/").status_code == 404
    assert client.get("/nonexistent/feed.atom").status_code == 404
    assert client.get("/nonexistent/search?q=foo").status_code == 404


# Endpoints scoped to a real inbox.
@pytest.mark.parametrize("path", [
    "/",
    "/today",
    "/yesterday",
    "/2024/",
    "/2024/05/",
    "/search",
    "/search?q=Linux",
    "/feed.atom",
])
def test_inbox_scoped_routes_200(client, inbox_name, path):
    assert client.get(f"/{inbox_name}{path}").status_code == 200


def test_year_out_of_range_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/1990/").status_code == 404
    # _max_archive_year() = current_year + 1; pick something solidly above.
    assert client.get(f"/{inbox_name}/2999/").status_code == 404


def test_month_out_of_range_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/2024/0/").status_code == 404
    assert client.get(f"/{inbox_name}/2024/13/").status_code == 404


def test_search_too_short(client, inbox_name):
    """Single-char query: server-side min-length check kicks in;
    response is 200 but renders the 'type at least N characters'
    notice rather than running a search."""
    r = client.get(f"/{inbox_name}/search?q=x")
    assert r.status_code == 200
    body = r.get_data(as_text=True)
    assert "characters" in body.lower()


def test_author_view_too_short_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/author/x").status_code == 404


def test_author_feed_too_short_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/author/x/feed.atom").status_code == 404


def test_request_id_round_trip(client):
    """X-Request-Id from the client should come back on the response;
    if absent, the server mints one."""
    r = client.get("/healthz", headers={"X-Request-Id": "abc-test-id"})
    assert r.headers.get("X-Request-Id") == "abc-test-id"
    r = client.get("/healthz")
    rid = r.headers.get("X-Request-Id")
    assert rid and rid != "abc-test-id"


def test_security_headers_present(client):
    r = client.get("/")
    for h in (
        "Content-Security-Policy",
        "Referrer-Policy",
        "X-Content-Type-Options",
        "X-Frame-Options",
    ):
        assert r.headers.get(h), f"missing header {h}"


def test_security_headers_values_pin_csp_contract(client):
    """Header presence isn't enough -- the *values* are the contract.
    A future refactor that left `script-src 'unsafe-inline'` in the
    CSP would silently re-enable the inline-script vector that
    blocked the thread-fold controller (#fixed in 1.12.2). Pin the
    exact directives that matter."""
    r = client.get("/")
    csp = r.headers.get("Content-Security-Policy", "")

    # default-src must be 'self' (no `*`, no permissive fallback).
    assert "default-src 'self'" in csp
    # script-src is the recurring footgun: no 'unsafe-inline', no
    # 'unsafe-eval', and only the explicit unpkg.com allowlist.
    assert "script-src" in csp
    assert "'unsafe-inline'" not in csp.split("script-src", 1)[1].split(";", 1)[0]
    assert "'unsafe-eval'" not in csp
    # Other crucial directives that block embed/iframe abuse.
    assert "frame-ancestors 'none'" in csp
    assert "base-uri 'self'" in csp
    # Other headers are short enough to pin exactly.
    assert r.headers["X-Content-Type-Options"] == "nosniff"
    assert r.headers["X-Frame-Options"] == "DENY"
    assert r.headers["Referrer-Policy"] == "strict-origin-when-cross-origin"


def test_hsts_emitted_only_on_https_requests(client):
    """HSTS is the one pin-the-browser-forever header in the bundle.
    It must NOT emit on plain-HTTP dev sessions (where it would brick
    the local workflow) and MUST emit on requests forwarded with
    X-Forwarded-Proto: https. max-age and the includeSubDomains
    directive are part of the contract; a refactor that drops either
    would silently weaken the production posture."""
    # Without the proxy header: no HSTS.
    r_plain = client.get("/")
    assert "Strict-Transport-Security" not in r_plain.headers

    # With X-Forwarded-Proto: https: HSTS emitted with the pinned value.
    r_https = client.get("/", headers={"X-Forwarded-Proto": "https"})
    hsts = r_https.headers.get("Strict-Transport-Security", "")
    assert hsts, "HSTS must emit when X-Forwarded-Proto=https"
    assert "max-age=" in hsts
    # max-age must be >= 6 months (15768000s); under that, browsers
    # treat the policy as advisory rather than enforced.
    import re
    m = re.search(r"max-age=(\d+)", hsts)
    assert m is not None
    assert int(m.group(1)) >= 15_768_000
    assert "includeSubDomains" in hsts


def test_author_page_autodiscovery_link(client, inbox_name):
    """The per-author HTML page advertises its atom feed via
    `<link rel="alternate" type="application/atom+xml">` in the head,
    so feed readers can subscribe from the page URL alone."""
    r = client.get(f"/{inbox_name}/author/example.com")
    assert r.status_code == 200
    body = r.data.decode()
    assert 'rel="alternate"' in body
    assert 'type="application/atom+xml"' in body
    assert f'/{inbox_name}/author/example.com/feed.atom' in body


def test_inbox_tracker_tile_links_to_atom(client, inbox_name):
    """The tracker tiles on the inbox dashboard surface a small `atom`
    link next to `all →` so the per-author feed is discoverable
    without visiting the HTML view first."""
    from mimir.inboxes import set_tracked_authors

    # Seed a tracker on the inbox so the tile section renders.
    set_tracked_authors(inbox_name, {"Examples": "example.com"})
    r = client.get(f"/{inbox_name}/")
    assert r.status_code == 200
    body = r.data.decode()
    assert f'/{inbox_name}/author/example.com/feed.atom' in body


def test_atom_feed_well_formed(client, inbox_name):
    import xml.etree.ElementTree as ET

    r = client.get(f"/{inbox_name}/feed.atom")
    assert r.status_code == 200
    assert r.mimetype.startswith("application/atom+xml")
    root = ET.fromstring(r.get_data())
    ns = {"a": "http://www.w3.org/2005/Atom"}
    # Required Atom fields on the feed element.
    assert root.find("a:id", ns) is not None
    assert root.find("a:title", ns) is not None
    assert root.find("a:updated", ns) is not None


# robots.txt / security.txt / sitemap.xml


def test_robots_txt(client):
    r = client.get("/robots.txt")
    assert r.status_code == 200
    assert r.mimetype == "text/plain"
    body = r.get_data(as_text=True)
    assert "User-agent: *" in body
    assert "Sitemap:" in body
    assert "/sitemap.xml" in body


def test_security_txt_404_when_unconfigured(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", None)
    assert client.get("/security.txt").status_code == 404
    assert client.get("/.well-known/security.txt").status_code == 404


def test_security_txt_when_configured(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", "mailto:test@example.com")
    monkeypatch.setattr(settings, "security_policy_url", None)
    monkeypatch.setattr(settings, "security_encryption_url", None)
    for url in ("/security.txt", "/.well-known/security.txt"):
        r = client.get(url)
        assert r.status_code == 200
        assert r.mimetype == "text/plain"
        body = r.get_data(as_text=True)
        assert "Contact: mailto:test@example.com" in body
        # Expires is dynamic; just confirm the field is present.
        assert "Expires:" in body
        assert "Preferred-Languages: en" in body


def test_security_txt_optional_fields_emitted_when_set(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", "mailto:test@example.com")
    monkeypatch.setattr(settings, "security_policy_url", "https://example.com/policy")
    monkeypatch.setattr(settings, "security_encryption_url", "https://example.com/pgp.asc")
    body = client.get("/security.txt").get_data(as_text=True)
    assert "Policy: https://example.com/policy" in body
    assert "Encryption: https://example.com/pgp.asc" in body


def _any_article_in(inbox_name):
    """Helper: return one (Article, inbox_name) pair from the running
    DB so the redirect tests have a real Message-ID to point at."""
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article, ArticleList, Inbox

    with SessionLocal() as s:
        return s.execute(
            select(Article)
            .join(ArticleList, ArticleList.article_id == Article.id)
            .join(Inbox, Inbox.id == ArticleList.inbox_id)
            .where(Inbox.name == inbox_name)
            .limit(1)
        ).scalar_one_or_none()


def test_global_message_id_lookup_redirect(client, inbox_name):
    art = _any_article_in(inbox_name)
    if art is None:
        pytest.skip("no articles in DB")
    r = client.get(f"/m/{art.message_id}", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    # Should redirect to a /<inbox>/<YYYY>/<MM>/<id> URL.
    assert loc.endswith(f"/{art.id}")
    assert r.headers.get("Cache-Control", "").startswith("public")


def test_message_id_404_unknown(client):
    assert client.get("/m/no-such-message-id-12345").status_code == 404


def test_inbox_scoped_message_id_redirect(client, inbox_name):
    art = _any_article_in(inbox_name)
    if art is None:
        pytest.skip("no articles in DB")
    r = client.get(f"/{inbox_name}/m/{art.message_id}", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    assert loc.startswith(f"/{inbox_name}/")
    assert loc.endswith(f"/{art.id}")


def test_sitemap_xml(client):
    """`/sitemap.xml` is the sitemap index: a `<sitemapindex>` of
    `<sitemap>` children, one per inbox sub-sitemap plus `/meta-sitemap.xml`.
    Cross-posts no longer collapse to one URL in this file — they're
    listed per-inbox in each sub-sitemap (the canonical <link> on the
    page tells crawlers which one wins)."""
    import xml.etree.ElementTree as ET

    _clear_sitemap_cache()
    r = client.get("/sitemap.xml")
    assert r.status_code == 200
    assert r.mimetype == "application/xml"
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    # Root element is <sitemapindex>, not <urlset>.
    assert root.tag.endswith("sitemapindex")
    sitemaps = root.findall("s:sitemap", ns)
    locs = {sm.find("s:loc", ns).text for sm in sitemaps}
    assert any(loc.endswith("/meta-sitemap.xml") for loc in locs)
    assert any(loc.endswith("/alpha/sitemap.xml") for loc in locs)
    assert any(loc.endswith("/beta/sitemap.xml") for loc in locs)


# ProxyFix: trusted_proxy_hops controls X-Forwarded-* honouring


def _build_app_with_hops(monkeypatch, hops: int):
    """Re-create the Flask app with `trusted_proxy_hops` patched.
    `create_app()` decides ProxyFix wiring at construction time."""
    from mimir.config import settings
    monkeypatch.setattr(settings, "trusted_proxy_hops", hops)
    from mimir import create_app
    return create_app()


def test_proxy_fix_off_when_hops_zero(monkeypatch):
    from werkzeug.middleware.proxy_fix import ProxyFix
    app = _build_app_with_hops(monkeypatch, 0)
    assert not isinstance(app.wsgi_app, ProxyFix)


def test_proxy_fix_wrapped_when_hops_positive(monkeypatch):
    from werkzeug.middleware.proxy_fix import ProxyFix
    app = _build_app_with_hops(monkeypatch, 1)
    assert isinstance(app.wsgi_app, ProxyFix)


def test_proxy_fix_unwraps_remote_addr_from_xff(monkeypatch):
    """End-to-end: with trusted_proxy_hops=1, request.remote_addr
    reflects X-Forwarded-For instead of the connection IP."""
    from flask import request
    app = _build_app_with_hops(monkeypatch, 1)
    captured: dict[str, str | None] = {}

    @app.route("/__probe_remote")
    def _probe():
        captured["remote"] = request.remote_addr
        captured["scheme"] = request.scheme
        return ""

    client = app.test_client()
    client.get(
        "/__probe_remote",
        environ_base={"REMOTE_ADDR": "10.30.30.2"},
        headers={
            "X-Forwarded-For": "203.0.113.7",
            "X-Forwarded-Proto": "https",
        },
    )
    assert captured["remote"] == "203.0.113.7"
    assert captured["scheme"] == "https"


def test_proxy_fix_off_keeps_connection_remote_addr(monkeypatch):
    """With hops=0, XFF is NOT honoured — request.remote_addr stays
    the connection IP. Guards against accidentally enabling ProxyFix
    on a directly-exposed app, where attackers could spoof XFF."""
    from flask import request
    app = _build_app_with_hops(monkeypatch, 0)
    captured: dict[str, str | None] = {}

    @app.route("/__probe_remote")
    def _probe():
        captured["remote"] = request.remote_addr
        return ""

    client = app.test_client()
    client.get(
        "/__probe_remote",
        environ_base={"REMOTE_ADDR": "10.30.30.2"},
        headers={"X-Forwarded-For": "203.0.113.7"},
    )
    assert captured["remote"] == "10.30.30.2"


# Access-log shape


def test_access_log_records_user_agent(client):
    """Regression: the structured access log captured `ua: null` for
    every request because the falsy check on `request.user_agent`
    depends on Werkzeug's UA parser recognising a browser, which
    misfires on non-browser UAs (curl, wget) and even some browsers
    in newer Werkzeug. Read the raw header instead."""
    import json
    import logging

    captured: list[str] = []

    class _Capture(logging.Handler):
        def emit(self, record):
            captured.append(record.getMessage())

    request_logger = logging.getLogger("mimir.request")
    prior = (request_logger.level, request_logger.disabled)
    # pytest's logging plugin marks unmanaged loggers as disabled
    # between tests; flip it back so emit() reaches our handler.
    request_logger.disabled = False
    request_logger.setLevel(logging.INFO)
    handler = _Capture()
    request_logger.addHandler(handler)
    try:
        client.get("/healthz", headers={"User-Agent": "probe-agent/1.0"})
    finally:
        request_logger.removeHandler(handler)
        request_logger.level, request_logger.disabled = prior

    assert captured, "no log line was emitted"
    payload = json.loads(captured[-1])
    assert payload["ua"] == "probe-agent/1.0"


# Phase 3: render-side canonical surface


def test_canonical_inbox_name_uses_canonical_id():
    from unittest.mock import MagicMock
    from mimir.web import _canonical_inbox_name

    art = MagicMock()
    art.canonical_inbox_id = 7
    # links: linux-fsdevel is canonical; alphabetical-first would be lkml.
    links = [(1, "lkml"), (7, "linux-fsdevel")]
    assert _canonical_inbox_name(art, links) == "linux-fsdevel"


def test_canonical_inbox_name_falls_back_alphabetical_when_null():
    from unittest.mock import MagicMock
    from mimir.web import _canonical_inbox_name

    art = MagicMock()
    art.canonical_inbox_id = None
    links = [(7, "linux-fsdevel"), (1, "lkml")]
    assert _canonical_inbox_name(art, links) == "linux-fsdevel"


def test_canonical_inbox_name_returns_none_for_orphan_article():
    from unittest.mock import MagicMock
    from mimir.web import _canonical_inbox_name

    art = MagicMock()
    art.canonical_inbox_id = None
    assert _canonical_inbox_name(art, []) is None


def test_canonical_url_for_combines_base_and_msg_url():
    from unittest.mock import MagicMock
    from datetime import datetime
    from mimir.web import _canonical_url_for

    art = MagicMock()
    art.id = 99
    art.canonical_inbox_id = 7
    art.date = datetime(2024, 5, 1)
    links = [(7, "linux-fsdevel")]
    assert (
        _canonical_url_for(art, links, base="https://ex.com")
        == "https://ex.com/linux-fsdevel/2024/05/99"
    )


def test_sitemap_cross_post_appears_in_each_linked_inbox(client):
    """art3 is cross-posted alpha+beta. In the per-inbox sitemap world,
    it is listed under *both* `/alpha/sitemap.xml` and
    `/beta/sitemap.xml` — each one is a real, crawlable URL, and the
    canonical `<link>` on the page itself tells search engines which
    to keep. The sitemap doesn't try to enforce one-canonical-URL-per-
    article anymore (that was the old global-sitemap design)."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article

    with SessionLocal() as s:
        art3 = s.execute(
            select(Article).where(Article.message_id == "art3@example.com")
        ).scalar_one()
        art_id = art3.id

    _clear_sitemap_cache()
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}

    def article_locs(inbox: str) -> list[str]:
        root = ET.fromstring(client.get(f"/{inbox}/sitemap.xml").get_data())
        return [
            u.find("s:loc", ns).text
            for u in root.findall("s:url", ns)
            if u.find("s:loc", ns).text.endswith(f"/{art_id}")
        ]

    alpha_locs = article_locs("alpha")
    beta_locs = article_locs("beta")
    assert len(alpha_locs) == 1 and "/alpha/" in alpha_locs[0]
    assert len(beta_locs) == 1 and "/beta/" in beta_locs[0]


def test_atom_feed_cross_post_id_is_canonical_in_either_feed(client):
    """The same cross-posted article surfaces in both /alpha/feed.atom
    and /beta/feed.atom. With canonical resolution, both feeds' entries
    for art3 must carry the SAME <id> — the canonical URL — so feed
    readers that key on <id> deduplicate across feeds."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article

    with SessionLocal() as s:
        art3 = s.execute(
            select(Article).where(Article.message_id == "art3@example.com")
        ).scalar_one()
        art_id = art3.id

    ns = {"a": "http://www.w3.org/2005/Atom"}

    def find_id_for(feed_xml: bytes, art_id: int) -> str | None:
        root = ET.fromstring(feed_xml)
        for entry in root.findall("a:entry", ns):
            link = entry.find("a:link[@rel='alternate']", ns)
            if link is not None and link.get("href", "").endswith(f"/{art_id}"):
                id_el = entry.find("a:id", ns)
                return id_el.text if id_el is not None else None
        return None

    alpha_feed = client.get("/alpha/feed.atom")
    beta_feed = client.get("/beta/feed.atom")
    assert alpha_feed.status_code == 200
    assert beta_feed.status_code == 200

    alpha_id = find_id_for(alpha_feed.get_data(), art_id)
    beta_id = find_id_for(beta_feed.get_data(), art_id)
    assert alpha_id is not None and beta_id is not None
    assert alpha_id == beta_id
    # Fallback is alphabetical-first → alpha.
    assert "alpha" in alpha_id


# Per-page title tags + sitemap <lastmod>


def _title_of(html: str) -> str:
    import re
    m = re.search(r"<title>(.*?)</title>", html, re.DOTALL)
    return m.group(1).strip() if m else ""


def _ingest_one_article(
    tmp_path,
    inbox_name: str,
    message_id: str,
    subject: str = "test",
    in_reply_to: str | None = None,
    to: str | None = None,
) -> tuple[int, str]:
    """Build a tiny pubinbox-shaped bare repo with one message and
    ingest it into `inbox_name`. Repoints the inbox's mirror_path at
    `tmp_path` so `read_message` can fetch the blob; returns
    `(article_id, /<inbox>/YYYY/MM/<id>)` for routing tests."""
    from dulwich.objects import Blob, Commit, Tree
    from dulwich.repo import Repo
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.ingest import ingest_epoch
    from mimir.models import Article, Inbox

    extra = b""
    if in_reply_to is not None:
        extra += b"In-Reply-To: <" + in_reply_to.encode() + b">\r\n"
    if to is not None:
        extra += b"To: " + to.encode() + b"\r\n"
    raw = (
        b"Message-ID: <" + message_id.encode() + b">\r\n"
        b"From: a@b.example\r\n"
        b"Subject: " + subject.encode() + b"\r\n"
        b"Date: Mon, 1 Jan 2024 00:00:00 +0000\r\n"
        + extra +
        b"\r\n"
        b"body"
    )
    repo_dir = tmp_path / "0.git"
    repo = Repo.init_bare(str(repo_dir), mkdir=True)
    blob = Blob.from_string(raw)
    repo.object_store.add_object(blob)
    tree = Tree()
    tree.add(b"m", 0o100644, blob.id)
    repo.object_store.add_object(tree)
    commit = Commit()
    commit.tree = tree.id
    commit.parents = []
    commit.author = commit.committer = b"test <t@x>"
    commit.commit_time = commit.author_time = 1700000000
    commit.commit_timezone = commit.author_timezone = 0
    commit.encoding = b"UTF-8"
    commit.message = b"add"
    repo.object_store.add_object(commit)
    repo.refs[b"HEAD"] = commit.id

    with SessionLocal() as s:
        ix = s.execute(select(Inbox).where(Inbox.name == inbox_name)).scalar_one()
        ix.mirror_path = str(tmp_path)
        s.commit()
        ingest_epoch(s, ix, "0.git", repo_dir, workers=1)
        art = s.execute(
            select(Article).where(Article.message_id == message_id)
        ).scalar_one()
        url = (
            f"/{inbox_name}/{art.date.year}/{art.date.month:02d}/{art.id}"
        )
        return art.id, url


def test_meta_index_title_is_just_site_name(client):
    title = _title_of(client.get("/").data.decode())
    assert title == "mimir"


def test_inbox_dashboard_title(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/").data.decode())
    assert title == f"{inbox_name} | mimir"


def test_search_title_includes_query(client, inbox_name):
    title = _title_of(
        client.get(f"/{inbox_name}/search?q=Linux").data.decode()
    )
    assert title == f"Search 'Linux' | {inbox_name} | mimir"


def test_search_title_when_no_query(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/search").data.decode())
    assert title == f"Search | {inbox_name} | mimir"


def test_year_archive_title(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/2024/").data.decode())
    assert title == f"2024 | {inbox_name} | mimir"


def test_month_archive_title(client, inbox_name):
    # Month label format is "Month YYYY" — just sanity-check the
    # separator + scope tokens are present.
    title = _title_of(client.get(f"/{inbox_name}/2024/05/").data.decode())
    assert title.endswith(f" | {inbox_name} | mimir")
    assert "2024" in title


def test_daily_today_title(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/today").data.decode())
    assert " | " in title
    assert title.endswith(f" | {inbox_name} | mimir")


def test_message_subject_truncated_to_80(client, tmp_path):
    """Long subjects (patch series with v17 RFC 23/47 etc.) get
    truncated at 80 chars in <title> so SERPs don't overflow.
    Drives the real route end-to-end with a freshly-ingested article
    rather than testing Jinja's filter in isolation."""
    long_subject = "x" * 200
    _, url = _ingest_one_article(
        tmp_path, "alpha", "trunc@example.com", subject=long_subject,
    )
    r = client.get(url)
    assert r.status_code == 200
    title = _title_of(r.data.decode())
    assert title.endswith(" | alpha | mimir")
    # The subject portion shouldn't be the full 200-char input.
    subject_part = title.rsplit(" | alpha | mimir", 1)[0]
    assert len(subject_part) <= 84  # Jinja truncate(80) keeps ~81 incl ellipsis
    assert subject_part != long_subject


def test_sitemap_index_sub_sitemap_lastmods(client):
    """The sitemap index emits a `<lastmod>` per sub-sitemap so
    crawlers can skip unchanged inboxes. With seeded data, alpha,
    beta, and the meta-sitemap all carry the global max 2024-03-01
    (art3's cross-post date)."""
    import xml.etree.ElementTree as ET

    _clear_sitemap_cache()
    r = client.get("/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    lastmods = {
        sm.find("s:loc", ns).text: (
            sm.find("s:lastmod", ns).text
            if sm.find("s:lastmod", ns) is not None
            else None
        )
        for sm in root.findall("s:sitemap", ns)
    }
    meta_loc = next(loc for loc in lastmods if loc.endswith("/meta-sitemap.xml"))
    alpha_loc = next(loc for loc in lastmods if loc.endswith("/alpha/sitemap.xml"))
    beta_loc = next(loc for loc in lastmods if loc.endswith("/beta/sitemap.xml"))
    assert lastmods[meta_loc] == "2024-03-01"
    assert lastmods[alpha_loc] == "2024-03-01"
    assert lastmods[beta_loc] == "2024-03-01"


def test_meta_sitemap_lastmod_is_global_max(client):
    """`/meta-sitemap.xml` is a one-URL urlset listing `/` with the
    global max article date as its lastmod."""
    import xml.etree.ElementTree as ET

    _clear_sitemap_cache()
    r = client.get("/meta-sitemap.xml")
    assert r.status_code == 200
    assert r.mimetype == "application/xml"
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    urls = root.findall("s:url", ns)
    assert len(urls) == 1
    assert urls[0].find("s:loc", ns).text.endswith("/")
    assert urls[0].find("s:lastmod", ns).text == "2024-03-01"


def test_inbox_sitemap_dashboard_lastmod_is_inbox_max(client):
    """First entry of `/<inbox>/sitemap.xml` is the inbox dashboard,
    with the per-inbox max as lastmod. alpha's range is 2024-01-01
    to 2024-03-01 (art3 cross-post); beta's is 2024-02-01 to
    2024-03-01."""
    import xml.etree.ElementTree as ET

    _clear_sitemap_cache()
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    for inbox in ("alpha", "beta"):
        root = ET.fromstring(client.get(f"/{inbox}/sitemap.xml").get_data())
        urls = root.findall("s:url", ns)
        assert urls[0].find("s:loc", ns).text.endswith(f"/{inbox}/")
        assert urls[0].find("s:lastmod", ns).text == "2024-03-01"


def test_inbox_sitemap_article_lastmod_matches_article_date(client):
    """In a per-inbox sitemap, the per-article `<lastmod>` is the
    article's own date in YYYY-MM-DD."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article

    with SessionLocal() as s:
        art1 = s.execute(
            select(Article).where(Article.message_id == "art1@example.com")
        ).scalar_one()
        art1_id = art1.id
        art1_date = art1.date

    _clear_sitemap_cache()
    r = client.get("/alpha/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    art1_lastmod = None
    for u in root.findall("s:url", ns):
        loc = u.find("s:loc", ns).text
        if loc.endswith(f"/{art1_id}"):
            lm = u.find("s:lastmod", ns)
            art1_lastmod = lm.text if lm is not None else None
            break
    assert art1_lastmod == art1_date.strftime("%Y-%m-%d")


def test_inbox_sitemap_lists_year_and_month_archives(client):
    """Year + month archives that actually have data appear as
    lastmod-less `<url>` entries (discovery anchors, not refresh
    signals). Empty months are skipped — `/alpha/2024/` and
    `/alpha/2024/01/` are present, but only months with messages."""
    import xml.etree.ElementTree as ET

    _clear_sitemap_cache()
    r = client.get("/alpha/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    locs = {u.find("s:loc", ns).text for u in root.findall("s:url", ns)}
    assert any(loc.endswith("/alpha/2024/") for loc in locs)
    # alpha has messages in 2024-01 (art1, art4) and 2024-03 (art3),
    # but not 2024-02.
    assert any(loc.endswith("/alpha/2024/01/") for loc in locs)
    assert any(loc.endswith("/alpha/2024/03/") for loc in locs)
    assert not any(loc.endswith("/alpha/2024/02/") for loc in locs)


def test_inbox_sitemap_404_for_unknown_inbox(client):
    """Unknown inbox slug returns 404 rather than rendering an empty
    sitemap."""
    r = client.get("/notreal/sitemap.xml")
    assert r.status_code == 404


def test_inbox_sitemap_articles_scoped_to_that_inbox(client):
    """Articles only linked to beta (art2) don't appear in alpha's
    sitemap, and vice versa."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article

    with SessionLocal() as s:
        art2 = s.execute(
            select(Article).where(Article.message_id == "art2@example.com")
        ).scalar_one()
        art2_id = art2.id

    _clear_sitemap_cache()
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    alpha_root = ET.fromstring(client.get("/alpha/sitemap.xml").get_data())
    alpha_locs = {u.find("s:loc", ns).text for u in alpha_root.findall("s:url", ns)}
    assert not any(loc.endswith(f"/{art2_id}") for loc in alpha_locs)
    beta_root = ET.fromstring(client.get("/beta/sitemap.xml").get_data())
    beta_locs = {u.find("s:loc", ns).text for u in beta_root.findall("s:url", ns)}
    assert any(loc.endswith(f"/{art2_id}") for loc in beta_locs)


def test_global_message_id_lookup_uses_canonical_inbox(client):
    """art3 is cross-posted alpha+beta. Setting canonical_inbox_id to
    beta makes /m/<id> redirect to /beta/.../<id>, not /alpha/.../<id>
    (which would be the alphabetical-first fallback)."""
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article, Inbox

    with SessionLocal() as s:
        beta = s.execute(select(Inbox).where(Inbox.name == "beta")).scalar_one()
        art = s.execute(
            select(Article).where(Article.message_id == "art3@example.com")
        ).scalar_one()
        art.canonical_inbox_id = beta.id
        s.commit()

    r = client.get("/m/art3@example.com", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    assert "/beta/" in loc
    assert "/alpha/" not in loc


def test_global_message_id_lookup_falls_back_to_alphabetical(client):
    """With canonical_inbox_id NULL (default for seeded art3), the
    redirect goes to alphabetical-first — alpha."""
    r = client.get("/m/art3@example.com", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    assert "/alpha/" in loc


# Per-page meta description + Open Graph + Twitter Card tags


def _meta_value(html: str, name_or_property: str) -> str | None:
    """Extract a <meta> tag's content. Matches both `name=` and
    `property=` since OG uses property and the rest use name."""
    import re
    pattern = (
        r'<meta\s+(?:property|name)="' + re.escape(name_or_property)
        + r'"\s+content="([^"]*)"'
    )
    m = re.search(pattern, html)
    return m.group(1) if m else None


def test_meta_index_emits_default_description(client):
    html = client.get("/").data.decode()
    desc = _meta_value(html, "description")
    assert desc == (
        "Indexed mailing-list archives, served from local "
        "public-inbox v2 mirrors."
    )


def test_inbox_dashboard_meta_description_starts_with_inbox_archive(client, inbox_name):
    """Either rich or fallback form: both lead with '<inbox> archive'."""
    html = client.get(f"/{inbox_name}/").data.decode()
    desc = _meta_value(html, "description")
    assert desc is not None
    assert desc.startswith(f"{inbox_name} archive")


def test_search_meta_description_with_query(client, inbox_name):
    html = client.get(f"/{inbox_name}/search?q=Linux").data.decode()
    desc = _meta_value(html, "description")
    assert desc == f"Search results for 'Linux' in {inbox_name}."


def test_search_meta_description_when_no_query(client, inbox_name):
    html = client.get(f"/{inbox_name}/search").data.decode()
    desc = _meta_value(html, "description")
    assert desc == f"Search the {inbox_name} archive by subject or author."


def test_og_tags_on_index_match_expected_values(client):
    html = client.get("/").data.decode()
    expected_desc = (
        "Indexed mailing-list archives, served from local "
        "public-inbox v2 mirrors."
    )
    assert _meta_value(html, "og:title") == "mimir"
    assert _meta_value(html, "og:type") == "website"
    assert _meta_value(html, "og:site_name") == "mimir"
    assert _meta_value(html, "og:url") == "http://localhost/"
    assert _meta_value(html, "og:description") == expected_desc


def test_og_type_article_on_message_page(client, tmp_path):
    """Message pages override og:type to 'article' (the rest of the
    site stays on the 'website' default). End-to-end via a real
    ingested article so we exercise the rendered tag, not the
    template source."""
    _, url = _ingest_one_article(
        tmp_path, "alpha", "ogtype@example.com",
    )
    r = client.get(url)
    assert r.status_code == 200
    assert _meta_value(r.data.decode(), "og:type") == "article"


def test_twitter_card_tags_match_og_pair(client, inbox_name):
    """twitter:title/description should mirror og:title/description so
    Twitter's preview matches whatever Slack/etc. show via OG. The
    card type bumped from `summary` to `summary_large_image` once the
    SVG wordmark og:image landed (2026-05-11 review)."""
    html = client.get(f"/{inbox_name}/").data.decode()
    assert _meta_value(html, "twitter:card") == "summary_large_image"
    assert _meta_value(html, "twitter:title") == _meta_value(html, "og:title")
    assert (
        _meta_value(html, "twitter:description")
        == _meta_value(html, "og:description")
    )
    assert _meta_value(html, "twitter:title") == f"{inbox_name} | mimir"
    # Image mirrors og:image.
    assert _meta_value(html, "twitter:image") == _meta_value(html, "og:image")
    assert _meta_value(html, "og:image").endswith("/og-image.svg")


def test_meta_description_inbox_uses_rich_form_when_stats_present(client):
    """Seeded alpha has 3 linked articles → stats.total>0 → description
    is the rich form: '<inbox> archive: N message(s) from <first> to
    <last>, indexed and searchable.' (NOT the bare fallback '<inbox>
    archive on <site>.')"""
    html = client.get("/alpha/").data.decode()
    desc = _meta_value(html, "description")
    assert desc is not None
    # Markers exclusive to the rich form.
    assert desc.startswith("alpha archive: ")
    assert "message" in desc
    assert "indexed and searchable" in desc


# JSON-LD structured data


def _json_ld_blocks(html: str) -> list[dict]:
    """Extract every <script type=application/ld+json> JSON payload."""
    import json
    import re
    out: list[dict] = []
    for m in re.finditer(
        r'<script type="application/ld\+json">(.*?)</script>',
        html, re.DOTALL,
    ):
        out.append(json.loads(m.group(1)))
    return out


def test_index_emits_website_json_ld(client):
    """`/` carries a WebSite schema with name, url, and description."""
    blocks = _json_ld_blocks(client.get("/").data.decode())
    assert len(blocks) == 1
    obj = blocks[0]
    assert obj["@context"] == "https://schema.org"
    assert obj["@type"] == "WebSite"
    assert obj["name"] == "mimir"
    assert obj["url"] == "http://localhost/"
    assert obj["description"] == (
        "Indexed mailing-list archives, served from local "
        "public-inbox v2 mirrors."
    )


def test_thread_summary_helper_counts_and_relative_time():
    """`_thread_summary` returns author_count (deduped by email) and a
    coarse relative-time string for the most-recent message. Drives
    the closed-state fold one-liner ('23 messages, 5 authors, 2h ago')."""
    from dataclasses import dataclass
    from datetime import datetime, timedelta, timezone
    from mimir.web import _thread_summary

    @dataclass
    class N:
        author: str
        date: datetime | None
        message_id: str = ""
        depth: int = 0

    now = datetime.now(timezone.utc)
    nodes = [
        N(author="Alice <a@x.example>", date=now - timedelta(days=2)),
        N(author="Alice <A@X.example>", date=now - timedelta(days=1)),  # dupe by email
        N(author="Bob <b@y.example>", date=now - timedelta(hours=3)),
        N(author=None, date=None),  # missing data; doesn't crash
    ]
    s = _thread_summary(nodes)
    # Alice (case-insensitive dedupe) + Bob = 2; None ignored.
    assert s["author_count"] == 2
    assert s["last_activity_rel"] == "3h ago"


def test_message_page_single_message_thread_skips_fold_scaffolding(
    client, tmp_path,
):
    """When a thread has exactly one message and no off-list parent,
    the whole `.thread-context` block is omitted: no fold scaffolding,
    no toolbar, no `<html>`-level data attrs, no fold-controller
    script context."""
    _, url = _ingest_one_article(
        tmp_path, "alpha", "fold-solo@example.com", subject="solo",
    )
    body = client.get(url).data.decode()
    assert "thread-context" not in body
    assert "data-thread-fold" not in body
    assert "data-thread-root=" not in body
    assert "data-fold-set=" not in body
    # thread-fold.js is loaded on every page (from base.html) but with no
    # data-thread-* attrs on <html> the controller short-circuits the
    # FOUC-free block and the event handlers find no .thread-context.
    assert 'src="/static/js/thread-fold.js"' in body


def _seed_three_message_thread(tmp_path, inbox_name):
    """Build a 3-message thread root → reply → reply-to-reply in ONE
    shared bare repo, so the inbox's mirror_path resolves blobs for
    every article (not just the last-ingested one).

    `_ingest_one_article` creates its own fresh `0.git` per call and
    repoints mirror_path; that's fine for single-message tests but
    breaks here -- viewing the root would 500 trying to look up the
    root's commit_sha in the *reply's* mirror. This helper appends
    each message as a separate commit in the same bare repo so all
    three resolve under one mirror_path.

    Returns a dict keyed by role ("root" / "reply" / "nested") with
    `(article_id, url, message_id)` tuples for each.
    """
    from dulwich.objects import Blob, Commit, Tree
    from dulwich.repo import Repo
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.ingest import ingest_epoch
    from mimir.models import Article, Inbox

    repo_dir = tmp_path / "0.git"
    repo = Repo.init_bare(str(repo_dir), mkdir=True)
    prev_commit = None

    def _add(message_id: str, subject: str, in_reply_to: str | None) -> None:
        nonlocal prev_commit
        extra = b""
        if in_reply_to is not None:
            extra += b"In-Reply-To: <" + in_reply_to.encode() + b">\r\n"
        raw = (
            b"Message-ID: <" + message_id.encode() + b">\r\n"
            b"From: a@b.example\r\n"
            b"Subject: " + subject.encode() + b"\r\n"
            b"Date: Mon, 1 Jan 2024 00:00:00 +0000\r\n"
            + extra +
            b"\r\n"
            b"body"
        )
        blob = Blob.from_string(raw)
        repo.object_store.add_object(blob)
        tree = Tree()
        tree.add(b"m", 0o100644, blob.id)
        repo.object_store.add_object(tree)
        commit = Commit()
        commit.tree = tree.id
        commit.parents = [prev_commit] if prev_commit else []
        commit.author = commit.committer = b"test <t@x>"
        # 1704067200 == 2024-01-01 00:00 UTC; bumped per message so each
        # commit is unique and threading order is stable.
        commit.commit_time = commit.author_time = 1704067200 + len(_added)
        commit.commit_timezone = commit.author_timezone = 0
        commit.encoding = b"UTF-8"
        commit.message = b"add"
        repo.object_store.add_object(commit)
        prev_commit = commit.id
        _added.append(message_id)

    _added: list[str] = []
    _add("fold-root@example.com", "root msg", None)
    _add("fold-reply@example.com", "Re: root msg", "fold-root@example.com")
    _add("fold-nested@example.com", "Re: root msg", "fold-reply@example.com")
    repo.refs[b"HEAD"] = prev_commit

    with SessionLocal() as s:
        ix = s.execute(select(Inbox).where(Inbox.name == inbox_name)).scalar_one()
        ix.mirror_path = str(tmp_path)
        s.commit()
        ingest_epoch(s, ix, "0.git", repo_dir, workers=1)
        out = {}
        for role, mid in [
            ("root", "fold-root@example.com"),
            ("reply", "fold-reply@example.com"),
            ("nested", "fold-nested@example.com"),
        ]:
            art = s.execute(
                select(Article).where(Article.message_id == mid)
            ).scalar_one()
            url = f"/{inbox_name}/{art.date.year}/{art.date.month:02d}/{art.id}"
            out[role] = (art.id, url, mid)
        return out


def test_message_page_thread_fold_context_is_root_when_viewing_root(
    client, tmp_path,
):
    """Viewing the thread root sets data-thread-context="root" on
    <html>; the controller script reads that and defaults the fold
    state to `partial` (vs `closed` for a deep reply)."""
    msgs = _seed_three_message_thread(tmp_path, "alpha")
    body = client.get(msgs["root"][1]).data.decode()
    assert 'data-thread-root="fold-root@example.com"' in body
    assert 'data-thread-context="root"' in body


def test_message_page_thread_fold_context_is_deep_for_replies(
    client, tmp_path,
):
    """Viewing any non-root message in a thread sets
    data-thread-context="deep" -- the controller defaults to `closed`
    so the body gets full real estate."""
    msgs = _seed_three_message_thread(tmp_path, "alpha")
    body = client.get(msgs["nested"][1]).data.decode()
    assert 'data-thread-root="fold-root@example.com"' in body
    assert 'data-thread-context="deep"' in body


def test_message_page_thread_fold_active_marker_on_current_li(
    client, tmp_path,
):
    """The tree <li> whose data-message-id matches the current view
    carries class="is-active"; the others carry no such class. The
    JS controller toggles this class on htmx:afterSwap, but the
    server's initial render has to set it correctly for the first
    paint (when JS hasn't run yet or is disabled)."""
    msgs = _seed_three_message_thread(tmp_path, "alpha")
    _, nested_url, nested_mid = msgs["nested"]
    body = client.get(nested_url).data.decode()

    # The active <li> markup: data-message-id matches current view AND
    # class="is-active". Use a regex-ish substring check; the exact
    # element ordering is set by the template.
    import re
    li_active_pattern = re.compile(
        r'<li[^>]*data-message-id="' + re.escape(nested_mid) +
        r'"[^>]*class="is-active"',
        re.DOTALL,
    )
    assert li_active_pattern.search(body) is not None, (
        "expected active <li> for current message; markup was: "
        + body[body.find("thread-list"):body.find("</ul>")]
    )

    # No other <li> carries .is-active. There are three <li> total
    # (root + reply + nested); one is active, two must not be.
    li_with_class = re.findall(r'<li[^>]*class="is-active"', body)
    assert len(li_with_class) == 1


def test_message_page_thread_fold_toolbar_summary_counts_match(
    client, tmp_path,
):
    """The closed-state summary line ("N messages, M authors, Th ago")
    inside .thread-summary must reflect the real thread shape -- the
    seeded 3-message thread has 3 distinct authors (each
    `_ingest_one_article` defaults to `a@b.example`, so the dedup ends
    up at 1 author). Pin both counts explicitly so a future change to
    the summary helper that drops uniqueness is caught."""
    msgs = _seed_three_message_thread(tmp_path, "alpha")
    body = client.get(msgs["root"][1]).data.decode()

    import re
    # Extract the .thread-summary span contents.
    m = re.search(
        r'<span class="thread-summary">(.*?)</span>',
        body, re.DOTALL,
    )
    assert m is not None, "thread-summary span missing"
    summary_text = " ".join(m.group(1).split())  # collapse whitespace
    # All three articles share author "a@b.example" -> dedupes to 1.
    assert "3 messages" in summary_text
    assert "1 author" in summary_text
    assert "1 authors" not in summary_text  # singular form
    # Date in seeded thread is Jan 2024; render falls back to absolute
    # YYYY-MM-DD beyond the 30-day relative window.
    assert "2024-01-01" in summary_text


def test_message_page_thread_fold_links_carry_htmx_attrs(
    client, tmp_path,
):
    """Every non-active tree <li> must carry an <a> with the full HTMX
    attribute set: hx-get, hx-target=#msg, hx-swap=outerHTML, and
    hx-push-url=true. Without them, intra-thread navigation falls
    back to full page reloads."""
    msgs = _seed_three_message_thread(tmp_path, "alpha")
    body = client.get(msgs["root"][1]).data.decode()

    import re
    # All <a> inside the actual thread-list <ul>. Anchor on the element
    # open tag so the slice doesn't include the earlier `.thread-list`
    # CSS rule in the <style> block.
    ul_start = body.index('<ul class="thread-list"')
    ul_end = body.index("</ul>", ul_start)
    list_block = body[ul_start:ul_end]
    anchors = re.findall(r'<a[^>]*>', list_block)
    # Every <li> -- active or not -- carries an <a> with HTMX attrs.
    # The active treatment is class-on-<li> + CSS, not anchor suppression:
    # that keeps the JS controller's class-toggle-on-swap path simple
    # (no DOM rewrites between active <span> and inactive <a>).
    assert len(anchors) == 3, f"expected 3 anchors, got {len(anchors)}: {anchors}"
    for a in anchors:
        assert "hx-get=" in a
        assert 'hx-target="#msg"' in a
        assert 'hx-swap="outerHTML"' in a
        assert 'hx-push-url="true"' in a


def test_message_page_thread_fold_script_loads_before_section(
    client, tmp_path,
):
    """thread-fold.js is loaded from /static/ with a synchronous
    <script src=...> in <head>. It must execute *before* the
    <section class="thread-context"> opens so that the FOUC-free
    setAttribute on <html> resolves before CSS evaluates the section's
    descendant rules. Otherwise a localStorage pin overriding the
    server's context default would cause a visible flash."""
    msgs = _seed_three_message_thread(tmp_path, "alpha")
    body = client.get(msgs["nested"][1]).data.decode()
    script_idx = body.index('src="/static/js/thread-fold.js"')
    section_idx = body.index('<section class="thread-context"')
    body_idx = body.index("<body")
    assert script_idx < body_idx, (
        "thread-fold.js must be loaded from <head>, not <body>, to run "
        "before the section paints"
    )
    assert script_idx < section_idx


def test_message_page_htmx_request_returns_body_partial(client, tmp_path):
    """When HX-Request: true is set, the message route returns only the
    <article id="msg"> partial -- no <html>, no <head>, no thread tree.
    That's what lets the client-side script swap intra-thread nav into
    `#msg` without re-rendering surrounding chrome. The partial must
    carry the *content* the user came for, not just an empty article
    wrapper: the headline/from/date header, the message body, and
    attachments if any."""
    _, url = _ingest_one_article(
        tmp_path, "alpha", "htmx-swap@example.com",
        subject="swap test subject 12345",
    )
    r = client.get(url, headers={"HX-Request": "true"})
    assert r.status_code == 200
    body = r.data.decode()

    # Outer shape: hx-swap=outerHTML on the link targets #msg, so the
    # response's root element must be <article id="msg" data-message-id=...>.
    assert body.lstrip().startswith("<article id=\"msg\""), (
        "HTMX partial must start with the swap-target element so "
        "hx-swap=outerHTML replaces #msg cleanly"
    )
    assert 'data-message-id="htmx-swap@example.com"' in body

    # Actual content present (not an empty wrapper).
    assert "swap test subject 12345" in body
    assert "<strong>From:</strong>" in body
    assert "<strong>Date:</strong>" in body
    assert 'class="message-body"' in body

    # No surrounding chrome -- the chrome must stay on the client.
    # Use stricter `<tag>` / `<tag ` patterns; bare "<head" would also
    # match "<header>" inside the article, which is legitimate.
    lower = body.lower()
    assert "<!doctype" not in lower
    assert "<html>" not in lower and "<html " not in lower
    assert "<head>" not in lower and "<head " not in lower
    assert "<body>" not in lower and "<body " not in lower
    assert "thread-context" not in body
    assert "thread-toolbar" not in body
    assert "thread-fold.js" not in body


def test_message_page_full_and_htmx_responses_share_article_content(
    client, tmp_path,
):
    """Full page render and HX-Request render must contain identical
    content inside <article id="msg">. Regression guard: a refactor
    that diverges the two render paths (e.g. one uses _message_body.html
    and the other inlines) would silently break HTMX swap parity."""
    _, url = _ingest_one_article(
        tmp_path, "alpha", "parity@example.com", subject="parity check",
    )
    full = client.get(url).data.decode()
    partial = client.get(url, headers={"HX-Request": "true"}).data.decode()

    # Extract the <article id="msg"...> ... </article> block from each.
    def article_block(html: str) -> str:
        start = html.index('<article id="msg"')
        end = html.index("</article>", start) + len("</article>")
        return html[start:end]

    assert article_block(full) == article_block(partial), (
        "Full-page and HTMX-partial responses must share the exact "
        "<article id=\"msg\"> contents; divergence breaks intra-thread "
        "swap parity."
    )


def test_message_page_htmx_request_on_unknown_message_404s(
    client, tmp_path,
):
    """HTMX requests at non-existent URLs must still 404 (not return an
    empty 200 partial). HTMX surfaces this to htmx:responseError so the
    client can react; a silent 200 with empty body would render a blank
    panel where the message should be."""
    # Seed one valid article so the inbox exists with a real mirror.
    _ingest_one_article(
        tmp_path, "alpha", "valid@example.com", subject="valid",
    )
    # Hit an article id that's 999999 above any real id; route 404s.
    r = client.get(
        "/alpha/2024/01/999999",
        headers={"HX-Request": "true"},
    )
    assert r.status_code == 404


def test_message_page_emits_discussion_forum_posting(client, tmp_path):
    """Message page graph contains DiscussionForumPosting with all
    required-for-rich-results fields populated."""
    art_id, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-fp@example.com", subject="hello world",
    )
    blocks = _json_ld_blocks(client.get(url).data.decode())
    assert len(blocks) == 1
    graph = blocks[0]["@graph"]
    posting = next(g for g in graph if g["@type"] == "DiscussionForumPosting")
    assert posting["headline"] == "hello world"
    assert posting["@id"].endswith(f"/{art_id}")
    assert posting["url"] == posting["@id"]
    assert posting["mainEntityOfPage"] == posting["@id"]
    assert posting["isPartOf"]["@type"] == "WebSite"
    assert posting["isPartOf"]["name"] == "alpha"
    assert posting["isPartOf"]["url"].endswith("/alpha/")
    # Default Date in _ingest_one_article is "Mon, 1 Jan 2024 00:00:00 +0000".
    assert posting["datePublished"].startswith("2024-01-01T00:00:00")
    assert posting["dateModified"] == posting["datePublished"]


def test_message_page_emits_breadcrumb_list(client, tmp_path):
    """The same @graph also carries a BreadcrumbList with the
    Site → Inbox → Subject chain."""
    art_id, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-bc@example.com", subject="brief subject",
    )
    blocks = _json_ld_blocks(client.get(url).data.decode())
    graph = blocks[0]["@graph"]
    bc = next(g for g in graph if g["@type"] == "BreadcrumbList")
    items = bc["itemListElement"]
    assert len(items) == 3
    assert items[0]["position"] == 1
    assert items[0]["name"] == "mimir"
    assert items[0]["item"].endswith("/")
    assert items[1]["position"] == 2
    assert items[1]["name"] == "alpha"
    assert items[1]["item"].endswith("/alpha/")
    assert items[2]["position"] == 3
    assert items[2]["name"] == "brief subject"
    assert items[2]["item"].endswith(f"/{art_id}")


def test_message_breadcrumb_subject_truncated_to_80(client, tmp_path):
    """Breadcrumb item names mirror the <title> truncation budget so
    SERP breadcrumb display doesn't blow out either."""
    long_subject = "y" * 200
    _, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-bclong@example.com", subject=long_subject,
    )
    graph = _json_ld_blocks(client.get(url).data.decode())[0]["@graph"]
    bc = next(g for g in graph if g["@type"] == "BreadcrumbList")
    last = bc["itemListElement"][-1]
    assert len(last["name"]) <= 80
    assert last["name"] != long_subject


def test_message_json_ld_author_uses_safe_from_redaction(client, tmp_path, monkeypatch):
    """Authors outside the email allowlist render as `<hidden>` in
    the HTML body — same redaction must apply to JSON-LD's
    author.name, otherwise the schema leaks what the page hides."""
    from mimir.config import settings
    monkeypatch.setattr(settings, "email_allowlist", [])  # nothing allowlisted
    _, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-redact@example.com",
    )
    graph = _json_ld_blocks(client.get(url).data.decode())[0]["@graph"]
    posting = next(g for g in graph if g["@type"] == "DiscussionForumPosting")
    # _ingest_one_article uses From: a@b.example — no name part, no
    # allowlist match → safe_from returns "<hidden>".
    assert posting["author"]["name"] == "<hidden>"


def test_message_json_ld_author_full_when_allowlisted(client, tmp_path, monkeypatch):
    """And the inverse: allowlisted senders flow through unredacted."""
    from mimir.config import settings
    monkeypatch.setattr(settings, "email_allowlist", ["@b.example"])
    _, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-allow@example.com",
    )
    graph = _json_ld_blocks(client.get(url).data.decode())[0]["@graph"]
    posting = next(g for g in graph if g["@type"] == "DiscussionForumPosting")
    assert "a@b.example" in posting["author"]["name"]


def test_search_page_does_not_emit_json_ld(client, inbox_name):
    """Routes without JSON-LD plumbing should not emit a stray empty
    block. Search is a representative example."""
    blocks = _json_ld_blocks(
        client.get(f"/{inbox_name}/search?q=Linux").data.decode()
    )
    assert blocks == []


def test_inbox_dashboard_emits_discussion_forum_json_ld(client, inbox_name):
    """The inbox dashboard ships a `DiscussionForum` payload so the
    page reads as a topical hub for crawlers. ItemList of active
    threads is included when threads exist; an empty test corpus
    yields no `mainEntity`, but the type/name/url still appear."""
    blocks = _json_ld_blocks(
        client.get(f"/{inbox_name}/").data.decode()
    )
    assert len(blocks) == 1
    payload = blocks[0]
    assert payload["@type"] == "DiscussionForum"
    assert payload["name"] == inbox_name
    assert payload["url"].endswith(f"/{inbox_name}/")


def test_inbox_dashboard_no_trackers_hides_section(client, inbox_name):
    """alpha has tracked_authors=NULL by default — the tracker grid
    should not render at all."""
    body = client.get(f"/{inbox_name}/").data.decode()
    assert "Latest from " not in body


def test_inbox_dashboard_with_trackers_renders_tile(client, inbox_name):
    """Configure a tracker via the service layer; the tile should
    render with the configured label."""
    from mimir.inboxes import set_tracked_authors
    set_tracked_authors(inbox_name, {"Carol Tracked": "carol@kernel.org"})
    body = client.get(f"/{inbox_name}/").data.decode()
    assert "Latest from Carol Tracked" in body


def test_off_list_parent_hint_surfaces_unindexed_list(client, tmp_path):
    """When the thread root has an off-list parent and the article's
    To: header points at a list-shaped address that doesn't match any
    configured inbox, the rendered thread tree should surface that
    address as a hover-only hint so the operator knows which list to
    add. The address rides in `data-tooltip=` rather than visible
    text so the line stays compact."""
    _, url = _ingest_one_article(
        tmp_path, "alpha", "hint-shown@example.com",
        in_reply_to="missing-parent@example.com",
        to="linux-arm-kernel@lists.infradead.org",
    )
    body = client.get(url).data.decode()
    assert "off-list ancestor" in body
    assert (
        'data-tooltip="hint: linux-arm-kernel@lists.infradead.org"' in body
    )
    # Placed below the trigger to escape the .thread-box overflow clip
    # that hides the default top-positioned tooltip on the first row.
    assert 'data-placement="bottom"' in body


def test_off_list_parent_hint_skips_already_configured_lists(client, tmp_path):
    """If the To: address matches a configured inbox's list_address,
    the hint must be suppressed — there's nothing to add, that list
    is already indexed."""
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Inbox

    with SessionLocal() as s:
        ix = s.execute(select(Inbox).where(Inbox.name == "alpha")).scalar_one()
        ix.list_address = "linux-arm-kernel@lists.infradead.org"
        s.commit()

    _, url = _ingest_one_article(
        tmp_path, "alpha", "hint-suppressed@example.com",
        in_reply_to="missing-parent-2@example.com",
        to="linux-arm-kernel@lists.infradead.org",
    )
    body = client.get(url).data.decode()
    assert "off-list ancestor" in body
    assert "linux-arm-kernel@lists.infradead.org" not in body


# Meta-sweep (issue #3): canonical, favicon/og:image, ItemList JSON-LD,
# subject normalisation, display_name filter, SITE_BASE_URL override.


def test_canonical_link_on_homepage(client):
    """Every emitted page carries a canonical. Pre-meta-sweep the
    homepage was missing one; now it pins itself."""
    html = client.get("/").data.decode()
    import re as _re
    m = _re.search(r'<link rel="canonical" href="([^"]+)"', html)
    assert m is not None
    href = m.group(1)
    assert href.endswith("/")
    assert href.startswith("http://") or href.startswith("https://")


def test_canonical_link_on_inbox_dashboard(client, inbox_name):
    html = client.get(f"/{inbox_name}/").data.decode()
    import re as _re
    m = _re.search(r'<link rel="canonical" href="([^"]+)"', html)
    assert m is not None
    assert m.group(1).endswith(f"/{inbox_name}/")


def test_index_json_ld_includes_inbox_item_list(client):
    """`/` ships ItemList of configured inboxes so search engines can
    treat it as a topical hub rather than a flat link list."""
    blocks = _json_ld_blocks(client.get("/").data.decode())
    assert len(blocks) == 1
    payload = blocks[0]
    assert payload["@type"] == "WebSite"
    assert "mainEntity" in payload
    ml = payload["mainEntity"]
    assert ml["@type"] == "ItemList"
    assert ml["numberOfItems"] >= 1
    assert all("position" in item for item in ml["itemListElement"])


def test_favicon_svg_served(client):
    r = client.get("/favicon.svg")
    assert r.status_code == 200
    assert r.mimetype == "image/svg+xml"
    assert b"<svg" in r.data


def test_og_image_svg_served(client):
    r = client.get("/og-image.svg")
    assert r.status_code == 200
    assert r.mimetype == "image/svg+xml"
    assert b"<svg" in r.data
    # site_name templated in.
    assert b"mimir" in r.data or b"ratatoskr" in r.data


def test_clean_subject_filter_collapses_whitespace():
    from mimir.web import _clean_subject_filter
    assert _clean_subject_filter("a\n  b") == "a b"
    assert _clean_subject_filter("a\tb\r\nc") == "a b c"
    assert _clean_subject_filter("  spaces  ") == "spaces"
    assert _clean_subject_filter(None) == ""
    assert _clean_subject_filter("") == ""


def test_display_name_filter_strips_address(client):
    from mimir.web import _display_name_filter
    assert _display_name_filter("Bob <bob@example.com>") == "Bob"
    assert _display_name_filter("bob@example.com") == "unknown sender"
    assert _display_name_filter(None) == "unknown sender"
    assert _display_name_filter("") == "unknown sender"


def test_site_base_url_override_forces_scheme(monkeypatch):
    """SITE_BASE_URL setting takes precedence over request.url_root —
    the production escape hatch for `http://` leaking through a
    misconfigured proxy chain."""
    from mimir import config
    monkeypatch.setattr(
        config.settings, "site_base_url", "https://forced.example.com",
    )
    from mimir import create_app
    c = create_app().test_client()
    html = c.get("/").data.decode()
    import re as _re
    m = _re.search(r'<link rel="canonical" href="([^"]+)"', html)
    assert m is not None
    assert m.group(1).startswith("https://forced.example.com/")
    # og:url and og:image also pick up the forced base.
    assert _meta_value(html, "og:url").startswith("https://forced.example.com/")
    assert _meta_value(html, "og:image").startswith("https://forced.example.com/")


# Year browse decade grouping (issue #4).


def test_year_decade_groups_groups_by_decade():
    from mimir.web import _year_decade_groups
    out = _year_decade_groups(1996, 2026)
    decades = [decade for decade, _ in out]
    assert decades == [2020, 2010, 2000, 1990]
    # Each list is descending within the decade.
    assert out[0][1] == [2026, 2025, 2024, 2023, 2022, 2021, 2020]
    assert out[3][1] == [1999, 1998, 1997, 1996]


def test_year_decade_groups_single_decade():
    from mimir.web import _year_decade_groups
    out = _year_decade_groups(2024, 2026)
    assert out == [(2020, [2026, 2025, 2024])]


def test_year_decade_groups_single_year():
    from mimir.web import _year_decade_groups
    assert _year_decade_groups(2025, 2025) == [(2020, [2025])]


def test_year_decade_groups_handles_decade_boundary():
    """1999 → 2010 spans 3 decades; each gets exactly the years that
    belong to it (no off-by-one wrap)."""
    from mimir.web import _year_decade_groups
    out = _year_decade_groups(1999, 2010)
    assert out == [
        (2010, [2010]),
        (2000, [2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000]),
        (1990, [1999]),
    ]


def test_year_decade_groups_returns_empty_when_inverted():
    from mimir.web import _year_decade_groups
    assert _year_decade_groups(2026, 1996) == []


def test_inbox_dashboard_year_browse_uses_decade_grouping(client, inbox_name):
    """Visual smoke: footer carries the `year-decade-list` class with
    a `<strong>YYYY0s</strong>` heading per decade present in the
    inbox's date range."""
    html = client.get(f"/{inbox_name}/").data.decode()
    # The seeded fixture covers 2024-2025 (sub-2020s range may or may
    # not include older years), so just check the structure rather
    # than specific decade values.
    assert "year-decade-list" in html or "Browse by year" not in html
