"""Status-code smoke tests for every public route.

Catches the routine "did I break the URL routing or break a template
unrelated to my actual change" regression with one cheap test per
endpoint. Runs against the seeded test DB (alpha + beta inboxes
with a few articles) set up by tests/conftest.py.
"""
import pytest


# Endpoints that don't depend on a configured inbox.
def test_meta_index(client):
    assert client.get("/").status_code == 200


def test_footer_includes_mimir_version(client):
    from mimir import __version__
    body = client.get("/").data.decode()
    assert f"Generated by mimir {__version__}." in body


def test_meta_index_pins_inbox_first(client, monkeypatch):
    """Seeded fixtures have alpha + beta. Without a pin, alpha shows
    first (alphabetical). Pinning beta surfaces it ahead of alpha."""
    from mimir.config import settings

    monkeypatch.setattr(settings, "pinned_inboxes", [])
    body = client.get("/").data.decode()
    assert body.find("/alpha/") < body.find("/beta/")

    monkeypatch.setattr(settings, "pinned_inboxes", ["beta"])
    body = client.get("/").data.decode()
    assert body.find("/beta/") < body.find("/alpha/")


def test_healthz(client):
    r = client.get("/healthz")
    assert r.status_code == 200
    assert r.headers.get("Cache-Control") == "no-store"


def test_readyz(client):
    assert client.get("/readyz").status_code == 200


def test_unknown_inbox_404(client):
    assert client.get("/nonexistent/").status_code == 404
    assert client.get("/nonexistent/today").status_code == 404
    assert client.get("/nonexistent/2024/").status_code == 404
    assert client.get("/nonexistent/2024/05/").status_code == 404
    assert client.get("/nonexistent/feed.atom").status_code == 404
    assert client.get("/nonexistent/search?q=foo").status_code == 404


# Endpoints scoped to a real inbox.
@pytest.mark.parametrize("path", [
    "/",
    "/today",
    "/yesterday",
    "/2024/",
    "/2024/05/",
    "/search",
    "/search?q=Linux",
    "/feed.atom",
])
def test_inbox_scoped_routes_200(client, inbox_name, path):
    assert client.get(f"/{inbox_name}{path}").status_code == 200


def test_year_out_of_range_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/1990/").status_code == 404
    # _max_archive_year() = current_year + 1; pick something solidly above.
    assert client.get(f"/{inbox_name}/2999/").status_code == 404


def test_month_out_of_range_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/2024/0/").status_code == 404
    assert client.get(f"/{inbox_name}/2024/13/").status_code == 404


def test_search_too_short(client, inbox_name):
    """Single-char query: server-side min-length check kicks in;
    response is 200 but renders the 'type at least N characters'
    notice rather than running a search."""
    r = client.get(f"/{inbox_name}/search?q=x")
    assert r.status_code == 200
    body = r.get_data(as_text=True)
    assert "characters" in body.lower()


def test_author_view_too_short_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/author/x").status_code == 404


def test_author_feed_too_short_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/author/x/feed.atom").status_code == 404


def test_request_id_round_trip(client):
    """X-Request-Id from the client should come back on the response;
    if absent, the server mints one."""
    r = client.get("/healthz", headers={"X-Request-Id": "abc-test-id"})
    assert r.headers.get("X-Request-Id") == "abc-test-id"
    r = client.get("/healthz")
    rid = r.headers.get("X-Request-Id")
    assert rid and rid != "abc-test-id"


def test_security_headers_present(client):
    r = client.get("/")
    for h in (
        "Content-Security-Policy",
        "Referrer-Policy",
        "X-Content-Type-Options",
        "X-Frame-Options",
    ):
        assert r.headers.get(h), f"missing header {h}"


def test_atom_feed_well_formed(client, inbox_name):
    import xml.etree.ElementTree as ET

    r = client.get(f"/{inbox_name}/feed.atom")
    assert r.status_code == 200
    assert r.mimetype.startswith("application/atom+xml")
    root = ET.fromstring(r.get_data())
    ns = {"a": "http://www.w3.org/2005/Atom"}
    # Required Atom fields on the feed element.
    assert root.find("a:id", ns) is not None
    assert root.find("a:title", ns) is not None
    assert root.find("a:updated", ns) is not None


# robots.txt / security.txt / sitemap.xml


def test_robots_txt(client):
    r = client.get("/robots.txt")
    assert r.status_code == 200
    assert r.mimetype == "text/plain"
    body = r.get_data(as_text=True)
    assert "User-agent: *" in body
    assert "Sitemap:" in body
    assert "/sitemap.xml" in body


def test_security_txt_404_when_unconfigured(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", None)
    assert client.get("/security.txt").status_code == 404
    assert client.get("/.well-known/security.txt").status_code == 404


def test_security_txt_when_configured(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", "mailto:test@example.com")
    monkeypatch.setattr(settings, "security_policy_url", None)
    monkeypatch.setattr(settings, "security_encryption_url", None)
    for url in ("/security.txt", "/.well-known/security.txt"):
        r = client.get(url)
        assert r.status_code == 200
        assert r.mimetype == "text/plain"
        body = r.get_data(as_text=True)
        assert "Contact: mailto:test@example.com" in body
        # Expires is dynamic; just confirm the field is present.
        assert "Expires:" in body
        assert "Preferred-Languages: en" in body


def test_security_txt_optional_fields_emitted_when_set(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", "mailto:test@example.com")
    monkeypatch.setattr(settings, "security_policy_url", "https://example.com/policy")
    monkeypatch.setattr(settings, "security_encryption_url", "https://example.com/pgp.asc")
    body = client.get("/security.txt").get_data(as_text=True)
    assert "Policy: https://example.com/policy" in body
    assert "Encryption: https://example.com/pgp.asc" in body


def _any_article_in(inbox_name):
    """Helper: return one (Article, inbox_name) pair from the running
    DB so the redirect tests have a real Message-ID to point at."""
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article, ArticleList, Inbox

    with SessionLocal() as s:
        return s.execute(
            select(Article)
            .join(ArticleList, ArticleList.article_id == Article.id)
            .join(Inbox, Inbox.id == ArticleList.inbox_id)
            .where(Inbox.name == inbox_name)
            .limit(1)
        ).scalar_one_or_none()


def test_global_message_id_lookup_redirect(client, inbox_name):
    art = _any_article_in(inbox_name)
    if art is None:
        pytest.skip("no articles in DB")
    r = client.get(f"/m/{art.message_id}", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    # Should redirect to a /<inbox>/<YYYY>/<MM>/<id> URL.
    assert loc.endswith(f"/{art.id}")
    assert r.headers.get("Cache-Control", "").startswith("public")


def test_message_id_404_unknown(client):
    assert client.get("/m/no-such-message-id-12345").status_code == 404


def test_inbox_scoped_message_id_redirect(client, inbox_name):
    art = _any_article_in(inbox_name)
    if art is None:
        pytest.skip("no articles in DB")
    r = client.get(f"/{inbox_name}/m/{art.message_id}", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    assert loc.startswith(f"/{inbox_name}/")
    assert loc.endswith(f"/{art.id}")


def test_sitemap_xml(client):
    import xml.etree.ElementTree as ET

    r = client.get("/sitemap.xml")
    assert r.status_code == 200
    assert r.mimetype == "application/xml"
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    urls = root.findall("s:url", ns)
    # Always at least the meta-index plus per-inbox dashboards.
    assert len(urls) > 0
    locs = {u.find("s:loc", ns).text for u in urls}
    # Meta-index is always present.
    assert any(loc.endswith("/") and loc.count("/") <= 3 for loc in locs)


# ProxyFix: trusted_proxy_hops controls X-Forwarded-* honouring


def _build_app_with_hops(monkeypatch, hops: int):
    """Re-create the Flask app with `trusted_proxy_hops` patched.
    `create_app()` decides ProxyFix wiring at construction time."""
    from mimir.config import settings
    monkeypatch.setattr(settings, "trusted_proxy_hops", hops)
    from mimir import create_app
    return create_app()


def test_proxy_fix_off_when_hops_zero(monkeypatch):
    from werkzeug.middleware.proxy_fix import ProxyFix
    app = _build_app_with_hops(monkeypatch, 0)
    assert not isinstance(app.wsgi_app, ProxyFix)


def test_proxy_fix_wrapped_when_hops_positive(monkeypatch):
    from werkzeug.middleware.proxy_fix import ProxyFix
    app = _build_app_with_hops(monkeypatch, 1)
    assert isinstance(app.wsgi_app, ProxyFix)


def test_proxy_fix_unwraps_remote_addr_from_xff(monkeypatch):
    """End-to-end: with trusted_proxy_hops=1, request.remote_addr
    reflects X-Forwarded-For instead of the connection IP."""
    from flask import request
    app = _build_app_with_hops(monkeypatch, 1)
    captured: dict[str, str | None] = {}

    @app.route("/__probe_remote")
    def _probe():
        captured["remote"] = request.remote_addr
        captured["scheme"] = request.scheme
        return ""

    client = app.test_client()
    client.get(
        "/__probe_remote",
        environ_base={"REMOTE_ADDR": "10.30.30.2"},
        headers={
            "X-Forwarded-For": "203.0.113.7",
            "X-Forwarded-Proto": "https",
        },
    )
    assert captured["remote"] == "203.0.113.7"
    assert captured["scheme"] == "https"


def test_proxy_fix_off_keeps_connection_remote_addr(monkeypatch):
    """With hops=0, XFF is NOT honoured — request.remote_addr stays
    the connection IP. Guards against accidentally enabling ProxyFix
    on a directly-exposed app, where attackers could spoof XFF."""
    from flask import request
    app = _build_app_with_hops(monkeypatch, 0)
    captured: dict[str, str | None] = {}

    @app.route("/__probe_remote")
    def _probe():
        captured["remote"] = request.remote_addr
        return ""

    client = app.test_client()
    client.get(
        "/__probe_remote",
        environ_base={"REMOTE_ADDR": "10.30.30.2"},
        headers={"X-Forwarded-For": "203.0.113.7"},
    )
    assert captured["remote"] == "10.30.30.2"


# Access-log shape


def test_access_log_records_user_agent(client):
    """Regression: the structured access log captured `ua: null` for
    every request because the falsy check on `request.user_agent`
    depends on Werkzeug's UA parser recognising a browser, which
    misfires on non-browser UAs (curl, wget) and even some browsers
    in newer Werkzeug. Read the raw header instead."""
    import json
    import logging

    captured: list[str] = []

    class _Capture(logging.Handler):
        def emit(self, record):
            captured.append(record.getMessage())

    request_logger = logging.getLogger("mimir.request")
    prior = (request_logger.level, request_logger.disabled)
    # pytest's logging plugin marks unmanaged loggers as disabled
    # between tests; flip it back so emit() reaches our handler.
    request_logger.disabled = False
    request_logger.setLevel(logging.INFO)
    handler = _Capture()
    request_logger.addHandler(handler)
    try:
        client.get("/healthz", headers={"User-Agent": "probe-agent/1.0"})
    finally:
        request_logger.removeHandler(handler)
        request_logger.level, request_logger.disabled = prior

    assert captured, "no log line was emitted"
    payload = json.loads(captured[-1])
    assert payload["ua"] == "probe-agent/1.0"


# Phase 3: render-side canonical surface


def test_canonical_inbox_name_uses_canonical_id():
    from unittest.mock import MagicMock
    from mimir.web import _canonical_inbox_name

    art = MagicMock()
    art.canonical_inbox_id = 7
    # links: linux-fsdevel is canonical; alphabetical-first would be lkml.
    links = [(1, "lkml"), (7, "linux-fsdevel")]
    assert _canonical_inbox_name(art, links) == "linux-fsdevel"


def test_canonical_inbox_name_falls_back_alphabetical_when_null():
    from unittest.mock import MagicMock
    from mimir.web import _canonical_inbox_name

    art = MagicMock()
    art.canonical_inbox_id = None
    links = [(7, "linux-fsdevel"), (1, "lkml")]
    assert _canonical_inbox_name(art, links) == "linux-fsdevel"


def test_canonical_inbox_name_returns_none_for_orphan_article():
    from unittest.mock import MagicMock
    from mimir.web import _canonical_inbox_name

    art = MagicMock()
    art.canonical_inbox_id = None
    assert _canonical_inbox_name(art, []) is None


def test_canonical_url_for_combines_base_and_msg_url():
    from unittest.mock import MagicMock
    from datetime import datetime
    from mimir.web import _canonical_url_for

    art = MagicMock()
    art.id = 99
    art.canonical_inbox_id = 7
    art.date = datetime(2024, 5, 1)
    links = [(7, "linux-fsdevel")]
    assert (
        _canonical_url_for(art, links, base="https://ex.com")
        == "https://ex.com/linux-fsdevel/2024/05/99"
    )


def test_sitemap_emits_no_duplicate_urls(client):
    """The seeded cross-post art3 (alpha+beta) must surface as exactly
    one URL in the sitemap, not one per linked inbox."""
    import xml.etree.ElementTree as ET

    r = client.get("/sitemap.xml")
    assert r.status_code == 200
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    locs = [u.find("s:loc", ns).text for u in root.findall("s:url", ns)]
    # Article-level URLs end in /<id>; meta-index and dashboards don't.
    article_locs = [loc for loc in locs if loc.rstrip("/").rsplit("/", 1)[-1].isdigit()]
    assert len(article_locs) == len(set(article_locs))


def test_sitemap_cross_post_uses_canonical_inbox(client):
    """art3 is cross-posted alpha+beta. With canonical_inbox_id=NULL,
    fallback is alphabetical-first ('alpha'). The sitemap entry for
    art3 must be the alpha URL, not beta."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article

    with SessionLocal() as s:
        art3 = s.execute(
            select(Article).where(Article.message_id == "art3@example.com")
        ).scalar_one()
        art_id = art3.id

    r = client.get("/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    locs = [u.find("s:loc", ns).text for u in root.findall("s:url", ns)]
    art3_locs = [loc for loc in locs if loc.endswith(f"/{art_id}")]
    assert len(art3_locs) == 1
    assert "/alpha/" in art3_locs[0]
    assert "/beta/" not in art3_locs[0]


def test_sitemap_cross_post_respects_canonical_inbox_id(client):
    """Setting canonical_inbox_id=beta.id flips art3's sitemap URL to
    /beta/. Confirms the canonical column is read, not just the
    alphabetical fallback."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article, Inbox

    # Bust the sitemap cache so the change is visible immediately.
    from mimir import cache
    cache.purge_expired()
    from mimir.models import CacheEntry
    from sqlalchemy import delete
    with SessionLocal() as s:
        s.execute(delete(CacheEntry))
        beta = s.execute(select(Inbox).where(Inbox.name == "beta")).scalar_one()
        art3 = s.execute(
            select(Article).where(Article.message_id == "art3@example.com")
        ).scalar_one()
        art3.canonical_inbox_id = beta.id
        art_id = art3.id
        s.commit()

    r = client.get("/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    locs = [u.find("s:loc", ns).text for u in root.findall("s:url", ns)]
    art3_locs = [loc for loc in locs if loc.endswith(f"/{art_id}")]
    assert len(art3_locs) == 1
    assert "/beta/" in art3_locs[0]


def test_atom_feed_cross_post_id_is_canonical_in_either_feed(client):
    """The same cross-posted article surfaces in both /alpha/feed.atom
    and /beta/feed.atom. With canonical resolution, both feeds' entries
    for art3 must carry the SAME <id> — the canonical URL — so feed
    readers that key on <id> deduplicate across feeds."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article

    with SessionLocal() as s:
        art3 = s.execute(
            select(Article).where(Article.message_id == "art3@example.com")
        ).scalar_one()
        art_id = art3.id

    ns = {"a": "http://www.w3.org/2005/Atom"}

    def find_id_for(feed_xml: bytes, art_id: int) -> str | None:
        root = ET.fromstring(feed_xml)
        for entry in root.findall("a:entry", ns):
            link = entry.find("a:link[@rel='alternate']", ns)
            if link is not None and link.get("href", "").endswith(f"/{art_id}"):
                id_el = entry.find("a:id", ns)
                return id_el.text if id_el is not None else None
        return None

    alpha_feed = client.get("/alpha/feed.atom")
    beta_feed = client.get("/beta/feed.atom")
    assert alpha_feed.status_code == 200
    assert beta_feed.status_code == 200

    alpha_id = find_id_for(alpha_feed.get_data(), art_id)
    beta_id = find_id_for(beta_feed.get_data(), art_id)
    assert alpha_id is not None and beta_id is not None
    assert alpha_id == beta_id
    # Fallback is alphabetical-first → alpha.
    assert "alpha" in alpha_id


# Per-page title tags + sitemap <lastmod>


def _title_of(html: str) -> str:
    import re
    m = re.search(r"<title>(.*?)</title>", html, re.DOTALL)
    return m.group(1).strip() if m else ""


def _ingest_one_article(
    tmp_path,
    inbox_name: str,
    message_id: str,
    subject: str = "test",
) -> tuple[int, str]:
    """Build a tiny pubinbox-shaped bare repo with one message and
    ingest it into `inbox_name`. Repoints the inbox's mirror_path at
    `tmp_path` so `read_message` can fetch the blob; returns
    `(article_id, /<inbox>/YYYY/MM/<id>)` for routing tests."""
    from dulwich.objects import Blob, Commit, Tree
    from dulwich.repo import Repo
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.ingest import ingest_epoch
    from mimir.models import Article, Inbox

    raw = (
        b"Message-ID: <" + message_id.encode() + b">\r\n"
        b"From: a@b.example\r\n"
        b"Subject: " + subject.encode() + b"\r\n"
        b"Date: Mon, 1 Jan 2024 00:00:00 +0000\r\n"
        b"\r\n"
        b"body"
    )
    repo_dir = tmp_path / "0.git"
    repo = Repo.init_bare(str(repo_dir), mkdir=True)
    blob = Blob.from_string(raw)
    repo.object_store.add_object(blob)
    tree = Tree()
    tree.add(b"m", 0o100644, blob.id)
    repo.object_store.add_object(tree)
    commit = Commit()
    commit.tree = tree.id
    commit.parents = []
    commit.author = commit.committer = b"test <t@x>"
    commit.commit_time = commit.author_time = 1700000000
    commit.commit_timezone = commit.author_timezone = 0
    commit.encoding = b"UTF-8"
    commit.message = b"add"
    repo.object_store.add_object(commit)
    repo.refs[b"HEAD"] = commit.id

    with SessionLocal() as s:
        ix = s.execute(select(Inbox).where(Inbox.name == inbox_name)).scalar_one()
        ix.mirror_path = str(tmp_path)
        s.commit()
        ingest_epoch(s, ix, "0.git", repo_dir, workers=1)
        art = s.execute(
            select(Article).where(Article.message_id == message_id)
        ).scalar_one()
        url = (
            f"/{inbox_name}/{art.date.year}/{art.date.month:02d}/{art.id}"
        )
        return art.id, url


def test_meta_index_title_is_just_site_name(client):
    title = _title_of(client.get("/").data.decode())
    assert title == "mimir"


def test_inbox_dashboard_title(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/").data.decode())
    assert title == f"{inbox_name} | mimir"


def test_search_title_includes_query(client, inbox_name):
    title = _title_of(
        client.get(f"/{inbox_name}/search?q=Linux").data.decode()
    )
    assert title == f"Search 'Linux' | {inbox_name} | mimir"


def test_search_title_when_no_query(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/search").data.decode())
    assert title == f"Search | {inbox_name} | mimir"


def test_year_archive_title(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/2024/").data.decode())
    assert title == f"2024 | {inbox_name} | mimir"


def test_month_archive_title(client, inbox_name):
    # Month label format is "Month YYYY" — just sanity-check the
    # separator + scope tokens are present.
    title = _title_of(client.get(f"/{inbox_name}/2024/05/").data.decode())
    assert title.endswith(f" | {inbox_name} | mimir")
    assert "2024" in title


def test_daily_today_title(client, inbox_name):
    title = _title_of(client.get(f"/{inbox_name}/today").data.decode())
    assert " | " in title
    assert title.endswith(f" | {inbox_name} | mimir")


def test_message_subject_truncated_to_80(client, tmp_path):
    """Long subjects (patch series with v17 RFC 23/47 etc.) get
    truncated at 80 chars in <title> so SERPs don't overflow.
    Drives the real route end-to-end with a freshly-ingested article
    rather than testing Jinja's filter in isolation."""
    long_subject = "x" * 200
    _, url = _ingest_one_article(
        tmp_path, "alpha", "trunc@example.com", subject=long_subject,
    )
    r = client.get(url)
    assert r.status_code == 200
    title = _title_of(r.data.decode())
    assert title.endswith(" | alpha | mimir")
    # The subject portion shouldn't be the full 200-char input.
    subject_part = title.rsplit(" | alpha | mimir", 1)[0]
    assert len(subject_part) <= 84  # Jinja truncate(80) keeps ~81 incl ellipsis
    assert subject_part != long_subject


def test_sitemap_meta_index_lastmod_is_global_max(client):
    """Seeded articles range 2024-01-01 to 2024-03-01 (art3 cross-post).
    The meta-index <lastmod> is the global max → 2024-03-01."""
    import xml.etree.ElementTree as ET
    r = client.get("/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    first = root.findall("s:url", ns)[0]
    assert first.find("s:loc", ns).text.endswith("/")
    assert first.find("s:lastmod", ns).text == "2024-03-01"


def test_sitemap_alpha_dashboard_lastmod_is_alpha_max(client):
    """alpha is linked to art1 (2024-01-01), art3 (2024-03-01), art4
    (2024-01-02) — max is 2024-03-01 (art3 cross-post)."""
    import xml.etree.ElementTree as ET
    r = client.get("/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    for u in root.findall("s:url", ns):
        if u.find("s:loc", ns).text.endswith("/alpha/"):
            assert u.find("s:lastmod", ns).text == "2024-03-01"
            return
    raise AssertionError("alpha dashboard not in sitemap")


def test_sitemap_beta_dashboard_lastmod_is_beta_max(client):
    """beta is linked to art2 (2024-02-01) and art3 (2024-03-01) —
    max is 2024-03-01."""
    import xml.etree.ElementTree as ET
    r = client.get("/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    for u in root.findall("s:url", ns):
        if u.find("s:loc", ns).text.endswith("/beta/"):
            assert u.find("s:lastmod", ns).text == "2024-03-01"
            return
    raise AssertionError("beta dashboard not in sitemap")


def test_sitemap_article_lastmod_matches_article_date(client):
    """For per-article entries, <lastmod> should match the article's
    own date in YYYY-MM-DD."""
    import xml.etree.ElementTree as ET
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article

    # Bust cache so the just-deployed change shows up.
    from mimir.models import CacheEntry
    from sqlalchemy import delete
    with SessionLocal() as s:
        s.execute(delete(CacheEntry))
        art1 = s.execute(
            select(Article).where(Article.message_id == "art1@example.com")
        ).scalar_one()
        s.commit()
        art1_id = art1.id
        art1_date = art1.date

    r = client.get("/sitemap.xml")
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    art1_lastmod = None
    for u in root.findall("s:url", ns):
        loc = u.find("s:loc", ns).text
        if loc.endswith(f"/{art1_id}"):
            lm = u.find("s:lastmod", ns)
            art1_lastmod = lm.text if lm is not None else None
            break
    assert art1_lastmod == art1_date.strftime("%Y-%m-%d")


def test_global_message_id_lookup_uses_canonical_inbox(client):
    """art3 is cross-posted alpha+beta. Setting canonical_inbox_id to
    beta makes /m/<id> redirect to /beta/.../<id>, not /alpha/.../<id>
    (which would be the alphabetical-first fallback)."""
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article, Inbox

    with SessionLocal() as s:
        beta = s.execute(select(Inbox).where(Inbox.name == "beta")).scalar_one()
        art = s.execute(
            select(Article).where(Article.message_id == "art3@example.com")
        ).scalar_one()
        art.canonical_inbox_id = beta.id
        s.commit()

    r = client.get("/m/art3@example.com", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    assert "/beta/" in loc
    assert "/alpha/" not in loc


def test_global_message_id_lookup_falls_back_to_alphabetical(client):
    """With canonical_inbox_id NULL (default for seeded art3), the
    redirect goes to alphabetical-first — alpha."""
    r = client.get("/m/art3@example.com", follow_redirects=False)
    assert r.status_code == 301
    loc = r.headers.get("Location", "")
    assert "/alpha/" in loc


# Per-page meta description + Open Graph + Twitter Card tags


def _meta_value(html: str, name_or_property: str) -> str | None:
    """Extract a <meta> tag's content. Matches both `name=` and
    `property=` since OG uses property and the rest use name."""
    import re
    pattern = (
        r'<meta\s+(?:property|name)="' + re.escape(name_or_property)
        + r'"\s+content="([^"]*)"'
    )
    m = re.search(pattern, html)
    return m.group(1) if m else None


def test_meta_index_emits_default_description(client):
    html = client.get("/").data.decode()
    desc = _meta_value(html, "description")
    assert desc == (
        "Indexed mailing-list archives, served from local "
        "public-inbox v2 mirrors."
    )


def test_inbox_dashboard_meta_description_starts_with_inbox_archive(client, inbox_name):
    """Either rich or fallback form: both lead with '<inbox> archive'."""
    html = client.get(f"/{inbox_name}/").data.decode()
    desc = _meta_value(html, "description")
    assert desc is not None
    assert desc.startswith(f"{inbox_name} archive")


def test_search_meta_description_with_query(client, inbox_name):
    html = client.get(f"/{inbox_name}/search?q=Linux").data.decode()
    desc = _meta_value(html, "description")
    assert desc == f"Search results for 'Linux' in {inbox_name}."


def test_search_meta_description_when_no_query(client, inbox_name):
    html = client.get(f"/{inbox_name}/search").data.decode()
    desc = _meta_value(html, "description")
    assert desc == f"Search the {inbox_name} archive by subject or author."


def test_og_tags_on_index_match_expected_values(client):
    html = client.get("/").data.decode()
    expected_desc = (
        "Indexed mailing-list archives, served from local "
        "public-inbox v2 mirrors."
    )
    assert _meta_value(html, "og:title") == "mimir"
    assert _meta_value(html, "og:type") == "website"
    assert _meta_value(html, "og:site_name") == "mimir"
    assert _meta_value(html, "og:url") == "http://localhost/"
    assert _meta_value(html, "og:description") == expected_desc


def test_og_type_article_on_message_page(client, tmp_path):
    """Message pages override og:type to 'article' (the rest of the
    site stays on the 'website' default). End-to-end via a real
    ingested article so we exercise the rendered tag, not the
    template source."""
    _, url = _ingest_one_article(
        tmp_path, "alpha", "ogtype@example.com",
    )
    r = client.get(url)
    assert r.status_code == 200
    assert _meta_value(r.data.decode(), "og:type") == "article"


def test_twitter_card_tags_match_og_pair(client, inbox_name):
    """twitter:title/description should mirror og:title/description so
    Twitter's preview matches whatever Slack/etc. show via OG."""
    html = client.get(f"/{inbox_name}/").data.decode()
    assert _meta_value(html, "twitter:card") == "summary"
    assert _meta_value(html, "twitter:title") == _meta_value(html, "og:title")
    assert (
        _meta_value(html, "twitter:description")
        == _meta_value(html, "og:description")
    )
    assert _meta_value(html, "twitter:title") == f"{inbox_name} | mimir"


def test_meta_description_inbox_uses_rich_form_when_stats_present(client):
    """Seeded alpha has 3 linked articles → stats.total>0 → description
    is the rich form: '<inbox> archive: N message(s) from <first> to
    <last>, indexed and searchable.' (NOT the bare fallback '<inbox>
    archive on <site>.')"""
    html = client.get("/alpha/").data.decode()
    desc = _meta_value(html, "description")
    assert desc is not None
    # Markers exclusive to the rich form.
    assert desc.startswith("alpha archive: ")
    assert "message" in desc
    assert "indexed and searchable" in desc


# JSON-LD structured data


def _json_ld_blocks(html: str) -> list[dict]:
    """Extract every <script type=application/ld+json> JSON payload."""
    import json
    import re
    out: list[dict] = []
    for m in re.finditer(
        r'<script type="application/ld\+json">(.*?)</script>',
        html, re.DOTALL,
    ):
        out.append(json.loads(m.group(1)))
    return out


def test_index_emits_website_json_ld(client):
    """`/` carries a WebSite schema with name, url, and description."""
    blocks = _json_ld_blocks(client.get("/").data.decode())
    assert len(blocks) == 1
    obj = blocks[0]
    assert obj["@context"] == "https://schema.org"
    assert obj["@type"] == "WebSite"
    assert obj["name"] == "mimir"
    assert obj["url"] == "http://localhost/"
    assert obj["description"] == (
        "Indexed mailing-list archives, served from local "
        "public-inbox v2 mirrors."
    )


def test_message_page_emits_discussion_forum_posting(client, tmp_path):
    """Message page graph contains DiscussionForumPosting with all
    required-for-rich-results fields populated."""
    art_id, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-fp@example.com", subject="hello world",
    )
    blocks = _json_ld_blocks(client.get(url).data.decode())
    assert len(blocks) == 1
    graph = blocks[0]["@graph"]
    posting = next(g for g in graph if g["@type"] == "DiscussionForumPosting")
    assert posting["headline"] == "hello world"
    assert posting["@id"].endswith(f"/{art_id}")
    assert posting["url"] == posting["@id"]
    assert posting["mainEntityOfPage"] == posting["@id"]
    assert posting["isPartOf"]["@type"] == "WebSite"
    assert posting["isPartOf"]["name"] == "alpha"
    assert posting["isPartOf"]["url"].endswith("/alpha/")
    # Default Date in _ingest_one_article is "Mon, 1 Jan 2024 00:00:00 +0000".
    assert posting["datePublished"].startswith("2024-01-01T00:00:00")
    assert posting["dateModified"] == posting["datePublished"]


def test_message_page_emits_breadcrumb_list(client, tmp_path):
    """The same @graph also carries a BreadcrumbList with the
    Site → Inbox → Subject chain."""
    art_id, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-bc@example.com", subject="brief subject",
    )
    blocks = _json_ld_blocks(client.get(url).data.decode())
    graph = blocks[0]["@graph"]
    bc = next(g for g in graph if g["@type"] == "BreadcrumbList")
    items = bc["itemListElement"]
    assert len(items) == 3
    assert items[0]["position"] == 1
    assert items[0]["name"] == "mimir"
    assert items[0]["item"].endswith("/")
    assert items[1]["position"] == 2
    assert items[1]["name"] == "alpha"
    assert items[1]["item"].endswith("/alpha/")
    assert items[2]["position"] == 3
    assert items[2]["name"] == "brief subject"
    assert items[2]["item"].endswith(f"/{art_id}")


def test_message_breadcrumb_subject_truncated_to_80(client, tmp_path):
    """Breadcrumb item names mirror the <title> truncation budget so
    SERP breadcrumb display doesn't blow out either."""
    long_subject = "y" * 200
    _, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-bclong@example.com", subject=long_subject,
    )
    graph = _json_ld_blocks(client.get(url).data.decode())[0]["@graph"]
    bc = next(g for g in graph if g["@type"] == "BreadcrumbList")
    last = bc["itemListElement"][-1]
    assert len(last["name"]) <= 80
    assert last["name"] != long_subject


def test_message_json_ld_author_uses_safe_from_redaction(client, tmp_path, monkeypatch):
    """Authors outside the email allowlist render as `<hidden>` in
    the HTML body — same redaction must apply to JSON-LD's
    author.name, otherwise the schema leaks what the page hides."""
    from mimir.config import settings
    monkeypatch.setattr(settings, "email_allowlist", [])  # nothing allowlisted
    _, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-redact@example.com",
    )
    graph = _json_ld_blocks(client.get(url).data.decode())[0]["@graph"]
    posting = next(g for g in graph if g["@type"] == "DiscussionForumPosting")
    # _ingest_one_article uses From: a@b.example — no name part, no
    # allowlist match → safe_from returns "<hidden>".
    assert posting["author"]["name"] == "<hidden>"


def test_message_json_ld_author_full_when_allowlisted(client, tmp_path, monkeypatch):
    """And the inverse: allowlisted senders flow through unredacted."""
    from mimir.config import settings
    monkeypatch.setattr(settings, "email_allowlist", ["@b.example"])
    _, url = _ingest_one_article(
        tmp_path, "alpha", "jsonld-allow@example.com",
    )
    graph = _json_ld_blocks(client.get(url).data.decode())[0]["@graph"]
    posting = next(g for g in graph if g["@type"] == "DiscussionForumPosting")
    assert "a@b.example" in posting["author"]["name"]


def test_search_page_does_not_emit_json_ld(client, inbox_name):
    """Routes without JSON-LD plumbing should not emit a stray empty
    block. Search is a representative example."""
    blocks = _json_ld_blocks(
        client.get(f"/{inbox_name}/search?q=Linux").data.decode()
    )
    assert blocks == []


def test_inbox_dashboard_does_not_emit_json_ld(client, inbox_name):
    """Same — only `/` and message pages have JSON-LD in this phase."""
    blocks = _json_ld_blocks(
        client.get(f"/{inbox_name}/").data.decode()
    )
    assert blocks == []


def test_inbox_dashboard_no_trackers_hides_section(client, inbox_name):
    """alpha has tracked_authors=NULL by default — the tracker grid
    should not render at all."""
    body = client.get(f"/{inbox_name}/").data.decode()
    assert "Latest from " not in body


def test_inbox_dashboard_with_trackers_renders_tile(client, inbox_name):
    """Configure a tracker via the service layer; the tile should
    render with the configured label."""
    from mimir.inboxes import set_tracked_authors
    set_tracked_authors(inbox_name, {"Carol Tracked": "carol@kernel.org"})
    body = client.get(f"/{inbox_name}/").data.decode()
    assert "Latest from Carol Tracked" in body
