"""Status-code smoke tests for every public route.

Catches the routine "did I break the URL routing or break a template
unrelated to my actual change" regression with one cheap test per
endpoint. Runs against the seeded test DB (alpha + beta inboxes
with a few articles) set up by tests/conftest.py.
"""
import pytest


# Endpoints that don't depend on a configured inbox.
def test_meta_index(client):
    assert client.get("/").status_code == 200


def test_footer_includes_mimir_version(client):
    from mimir import __version__
    body = client.get("/").data.decode()
    assert f"Generated by mimir {__version__}." in body


def test_meta_index_pins_inbox_first(client, monkeypatch):
    """Seeded fixtures have alpha + beta. Without a pin, alpha shows
    first (alphabetical). Pinning beta surfaces it ahead of alpha."""
    from mimir.config import settings

    monkeypatch.setattr(settings, "pinned_inboxes", [])
    body = client.get("/").data.decode()
    assert body.find("/alpha/") < body.find("/beta/")

    monkeypatch.setattr(settings, "pinned_inboxes", ["beta"])
    body = client.get("/").data.decode()
    assert body.find("/beta/") < body.find("/alpha/")


def test_healthz(client):
    r = client.get("/healthz")
    assert r.status_code == 200
    assert r.headers.get("Cache-Control") == "no-store"


def test_readyz(client):
    assert client.get("/readyz").status_code == 200


def test_unknown_inbox_404(client):
    assert client.get("/nonexistent/").status_code == 404
    assert client.get("/nonexistent/today").status_code == 404
    assert client.get("/nonexistent/2024/").status_code == 404
    assert client.get("/nonexistent/2024/05/").status_code == 404
    assert client.get("/nonexistent/feed.atom").status_code == 404
    assert client.get("/nonexistent/search?q=foo").status_code == 404


# Endpoints scoped to a real inbox.
@pytest.mark.parametrize("path", [
    "/",
    "/today",
    "/yesterday",
    "/2024/",
    "/2024/05/",
    "/search",
    "/search?q=Linux",
    "/feed.atom",
])
def test_inbox_scoped_routes_200(client, inbox_name, path):
    assert client.get(f"/{inbox_name}{path}").status_code == 200


def test_year_out_of_range_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/1990/").status_code == 404
    # _max_archive_year() = current_year + 1; pick something solidly above.
    assert client.get(f"/{inbox_name}/2999/").status_code == 404


def test_month_out_of_range_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/2024/0/").status_code == 404
    assert client.get(f"/{inbox_name}/2024/13/").status_code == 404


def test_search_too_short(client, inbox_name):
    """Single-char query: server-side min-length check kicks in;
    response is 200 but renders the 'type at least N characters'
    notice rather than running a search."""
    r = client.get(f"/{inbox_name}/search?q=x")
    assert r.status_code == 200
    body = r.get_data(as_text=True)
    assert "characters" in body.lower()


def test_author_view_too_short_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/author/x").status_code == 404


def test_author_feed_too_short_404(client, inbox_name):
    assert client.get(f"/{inbox_name}/author/x/feed.atom").status_code == 404


def test_request_id_round_trip(client):
    """X-Request-Id from the client should come back on the response;
    if absent, the server mints one."""
    r = client.get("/healthz", headers={"X-Request-Id": "abc-test-id"})
    assert r.headers.get("X-Request-Id") == "abc-test-id"
    r = client.get("/healthz")
    rid = r.headers.get("X-Request-Id")
    assert rid and rid != "abc-test-id"


def test_security_headers_present(client):
    r = client.get("/")
    for h in (
        "Content-Security-Policy",
        "Referrer-Policy",
        "X-Content-Type-Options",
        "X-Frame-Options",
    ):
        assert r.headers.get(h), f"missing header {h}"


def test_atom_feed_well_formed(client, inbox_name):
    import xml.etree.ElementTree as ET

    r = client.get(f"/{inbox_name}/feed.atom")
    assert r.status_code == 200
    assert r.mimetype.startswith("application/atom+xml")
    root = ET.fromstring(r.get_data())
    ns = {"a": "http://www.w3.org/2005/Atom"}
    # Required Atom fields on the feed element.
    assert root.find("a:id", ns) is not None
    assert root.find("a:title", ns) is not None
    assert root.find("a:updated", ns) is not None


# robots.txt / security.txt / sitemap.xml


def test_robots_txt(client):
    r = client.get("/robots.txt")
    assert r.status_code == 200
    assert r.mimetype == "text/plain"
    body = r.get_data(as_text=True)
    assert "User-agent: *" in body
    assert "Sitemap:" in body
    assert "/sitemap.xml" in body


def test_security_txt_404_when_unconfigured(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", None)
    assert client.get("/security.txt").status_code == 404
    assert client.get("/.well-known/security.txt").status_code == 404


def test_security_txt_when_configured(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", "mailto:test@example.com")
    monkeypatch.setattr(settings, "security_policy_url", None)
    monkeypatch.setattr(settings, "security_encryption_url", None)
    for url in ("/security.txt", "/.well-known/security.txt"):
        r = client.get(url)
        assert r.status_code == 200
        assert r.mimetype == "text/plain"
        body = r.get_data(as_text=True)
        assert "Contact: mailto:test@example.com" in body
        # Expires is dynamic; just confirm the field is present.
        assert "Expires:" in body
        assert "Preferred-Languages: en" in body


def test_security_txt_optional_fields_emitted_when_set(client, monkeypatch):
    from mimir.config import settings

    monkeypatch.setattr(settings, "security_contact", "mailto:test@example.com")
    monkeypatch.setattr(settings, "security_policy_url", "https://example.com/policy")
    monkeypatch.setattr(settings, "security_encryption_url", "https://example.com/pgp.asc")
    body = client.get("/security.txt").get_data(as_text=True)
    assert "Policy: https://example.com/policy" in body
    assert "Encryption: https://example.com/pgp.asc" in body


def _any_article_in(inbox_name):
    """Helper: return one (Article, inbox_name) pair from the running
    DB so the redirect tests have a real Message-ID to point at."""
    from sqlalchemy import select
    from mimir.extensions import SessionLocal
    from mimir.models import Article, ArticleList, Inbox

    with SessionLocal() as s:
        return s.execute(
            select(Article)
            .join(ArticleList, ArticleList.article_id == Article.id)
            .join(Inbox, Inbox.id == ArticleList.inbox_id)
            .where(Inbox.name == inbox_name)
            .limit(1)
        ).scalar_one_or_none()


def test_global_message_id_lookup_redirect(client, inbox_name):
    art = _any_article_in(inbox_name)
    if art is None:
        pytest.skip("no articles in DB")
    r = client.get(f"/m/{art.message_id}", follow_redirects=False)
    assert r.status_code == 302
    loc = r.headers.get("Location", "")
    # Should redirect to a /<inbox>/<YYYY>/<MM>/<id> URL.
    assert loc.endswith(f"/{art.id}")
    assert r.headers.get("Cache-Control", "").startswith("public")


def test_message_id_404_unknown(client):
    assert client.get("/m/no-such-message-id-12345").status_code == 404


def test_inbox_scoped_message_id_redirect(client, inbox_name):
    art = _any_article_in(inbox_name)
    if art is None:
        pytest.skip("no articles in DB")
    r = client.get(f"/{inbox_name}/m/{art.message_id}", follow_redirects=False)
    assert r.status_code == 302
    loc = r.headers.get("Location", "")
    assert loc.startswith(f"/{inbox_name}/")
    assert loc.endswith(f"/{art.id}")


def test_sitemap_xml(client):
    import xml.etree.ElementTree as ET

    r = client.get("/sitemap.xml")
    assert r.status_code == 200
    assert r.mimetype == "application/xml"
    root = ET.fromstring(r.get_data())
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    urls = root.findall("s:url", ns)
    # Always at least the meta-index plus per-inbox dashboards.
    assert len(urls) > 0
    locs = {u.find("s:loc", ns).text for u in urls}
    # Meta-index is always present.
    assert any(loc.endswith("/") and loc.count("/") <= 3 for loc in locs)


# ProxyFix: trusted_proxy_hops controls X-Forwarded-* honouring


def _build_app_with_hops(monkeypatch, hops: int):
    """Re-create the Flask app with `trusted_proxy_hops` patched.
    `create_app()` decides ProxyFix wiring at construction time."""
    from mimir.config import settings
    monkeypatch.setattr(settings, "trusted_proxy_hops", hops)
    from mimir import create_app
    return create_app()


def test_proxy_fix_off_when_hops_zero(monkeypatch):
    from werkzeug.middleware.proxy_fix import ProxyFix
    app = _build_app_with_hops(monkeypatch, 0)
    assert not isinstance(app.wsgi_app, ProxyFix)


def test_proxy_fix_wrapped_when_hops_positive(monkeypatch):
    from werkzeug.middleware.proxy_fix import ProxyFix
    app = _build_app_with_hops(monkeypatch, 1)
    assert isinstance(app.wsgi_app, ProxyFix)


def test_proxy_fix_unwraps_remote_addr_from_xff(monkeypatch):
    """End-to-end: with trusted_proxy_hops=1, request.remote_addr
    reflects X-Forwarded-For instead of the connection IP."""
    from flask import request
    app = _build_app_with_hops(monkeypatch, 1)
    captured: dict[str, str | None] = {}

    @app.route("/__probe_remote")
    def _probe():
        captured["remote"] = request.remote_addr
        captured["scheme"] = request.scheme
        return ""

    client = app.test_client()
    client.get(
        "/__probe_remote",
        environ_base={"REMOTE_ADDR": "10.30.30.2"},
        headers={
            "X-Forwarded-For": "203.0.113.7",
            "X-Forwarded-Proto": "https",
        },
    )
    assert captured["remote"] == "203.0.113.7"
    assert captured["scheme"] == "https"


def test_proxy_fix_off_keeps_connection_remote_addr(monkeypatch):
    """With hops=0, XFF is NOT honoured — request.remote_addr stays
    the connection IP. Guards against accidentally enabling ProxyFix
    on a directly-exposed app, where attackers could spoof XFF."""
    from flask import request
    app = _build_app_with_hops(monkeypatch, 0)
    captured: dict[str, str | None] = {}

    @app.route("/__probe_remote")
    def _probe():
        captured["remote"] = request.remote_addr
        return ""

    client = app.test_client()
    client.get(
        "/__probe_remote",
        environ_base={"REMOTE_ADDR": "10.30.30.2"},
        headers={"X-Forwarded-For": "203.0.113.7"},
    )
    assert captured["remote"] == "10.30.30.2"


# Access-log shape


def test_access_log_records_user_agent(client):
    """Regression: the structured access log captured `ua: null` for
    every request because the falsy check on `request.user_agent`
    depends on Werkzeug's UA parser recognising a browser, which
    misfires on non-browser UAs (curl, wget) and even some browsers
    in newer Werkzeug. Read the raw header instead."""
    import json
    import logging

    captured: list[str] = []

    class _Capture(logging.Handler):
        def emit(self, record):
            captured.append(record.getMessage())

    request_logger = logging.getLogger("mimir.request")
    prior = (request_logger.level, request_logger.disabled)
    # pytest's logging plugin marks unmanaged loggers as disabled
    # between tests; flip it back so emit() reaches our handler.
    request_logger.disabled = False
    request_logger.setLevel(logging.INFO)
    handler = _Capture()
    request_logger.addHandler(handler)
    try:
        client.get("/healthz", headers={"User-Agent": "probe-agent/1.0"})
    finally:
        request_logger.removeHandler(handler)
        request_logger.level, request_logger.disabled = prior

    assert captured, "no log line was emitted"
    payload = json.loads(captured[-1])
    assert payload["ua"] == "probe-agent/1.0"
