"""add mainline_commits + commits_walked_to_sha cursor

Revision ID: 1c6472397d92
Revises: ae03d25e7347
Create Date: 2026-05-14 14:30:17.866054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6472397d92'
down_revision: Union[str, Sequence[str], None] = 'ae03d25e7347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mainline_commits',
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('tree_name', sa.String(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('commit_sha', 'message_id')
    )
    op.create_index(op.f('ix_mainline_commits_message_id'), 'mainline_commits', ['message_id'], unique=False)
    op.create_index(op.f('ix_mainline_commits_tree_name'), 'mainline_commits', ['tree_name'], unique=False)
    op.add_column('mainline_state', sa.Column('commits_walked_to_sha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mainline_state', 'commits_walked_to_sha')
    op.drop_index(op.f('ix_mainline_commits_tree_name'), table_name='mainline_commits')
    op.drop_index(op.f('ix_mainline_commits_message_id'), table_name='mainline_commits')
    op.drop_table('mainline_commits')
    # ### end Alembic commands ###
