"""add thread_parent column

Revision ID: 220d07a097d8
Revises: 27d30c45991d
Create Date: 2026-05-03 11:53:27.230214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220d07a097d8'
down_revision: Union[str, Sequence[str], None] = '27d30c45991d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('thread_parent', sa.String(), nullable=True))
    op.create_index(op.f('ix_articles_thread_parent'), 'articles', ['thread_parent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_thread_parent'), table_name='articles')
    op.drop_column('articles', 'thread_parent')
    # ### end Alembic commands ###
