"""initial schema (lean: git as backing store)

Revision ID: 27d30c45991d
Revises: 
Create Date: 2026-05-01 00:14:12.752732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d30c45991d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('epoch', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('in_reply_to', sa.String(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_date'), 'articles', ['date'], unique=False)
    op.create_index(op.f('ix_articles_epoch'), 'articles', ['epoch'], unique=False)
    op.create_index(op.f('ix_articles_in_reply_to'), 'articles', ['in_reply_to'], unique=False)
    op.create_index(op.f('ix_articles_message_id'), 'articles', ['message_id'], unique=True)
    op.create_table('ingest_state',
    sa.Column('epoch', sa.String(), nullable=False),
    sa.Column('last_commit_sha', sa.String(), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('epoch')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('ingest_state')
    op.drop_index(op.f('ix_articles_message_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_in_reply_to'), table_name='articles')
    op.drop_index(op.f('ix_articles_epoch'), table_name='articles')
    op.drop_index(op.f('ix_articles_date'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
