"""add subsystems + mainline_state tables

Revision ID: 4ee3d114b2b5
Revises: 285e3b1a545e
Create Date: 2026-05-14 13:50:05.330430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee3d114b2b5'
down_revision: Union[str, Sequence[str], None] = '285e3b1a545e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mainline_state',
    sa.Column('tree_name', sa.String(), nullable=False),
    sa.Column('last_commit_sha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tree_name')
    )
    op.create_table('subsystems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystems_name'), 'subsystems', ['name'], unique=False)
    op.create_table('subsystem_maintainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsystem_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subsystem_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_maintainers_address'), 'subsystem_maintainers', ['address'], unique=False)
    op.create_index(op.f('ix_subsystem_maintainers_role'), 'subsystem_maintainers', ['role'], unique=False)
    op.create_index(op.f('ix_subsystem_maintainers_subsystem_id'), 'subsystem_maintainers', ['subsystem_id'], unique=False)
    op.create_table('subsystem_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsystem_id', sa.Integer(), nullable=False),
    sa.Column('glob', sa.String(), nullable=False),
    sa.Column('is_exclude', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subsystem_id'], ['subsystems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_paths_subsystem_id'), 'subsystem_paths', ['subsystem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subsystem_paths_subsystem_id'), table_name='subsystem_paths')
    op.drop_table('subsystem_paths')
    op.drop_index(op.f('ix_subsystem_maintainers_subsystem_id'), table_name='subsystem_maintainers')
    op.drop_index(op.f('ix_subsystem_maintainers_role'), table_name='subsystem_maintainers')
    op.drop_index(op.f('ix_subsystem_maintainers_address'), table_name='subsystem_maintainers')
    op.drop_table('subsystem_maintainers')
    op.drop_index(op.f('ix_subsystems_name'), table_name='subsystems')
    op.drop_table('subsystems')
    op.drop_table('mainline_state')
    # ### end Alembic commands ###
