"""add article_files table

Revision ID: ae03d25e7347
Revises: 4ee3d114b2b5
Create Date: 2026-05-14 13:58:46.902942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae03d25e7347'
down_revision: Union[str, Sequence[str], None] = '4ee3d114b2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_files',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'path')
    )
    op.create_index(op.f('ix_article_files_path'), 'article_files', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_files_path'), table_name='article_files')
    op.drop_table('article_files')
    # ### end Alembic commands ###
