"""add article_trailers table

Revision ID: bd2c6a41c4d5
Revises: 2892bee6ba19
Create Date: 2026-05-15 01:43:56.586050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd2c6a41c4d5'
down_revision: Union[str, Sequence[str], None] = '2892bee6ba19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_trailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('address_normalized', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_trailers_article_id'), 'article_trailers', ['article_id'], unique=False)
    op.create_index('ix_article_trailers_role_addr', 'article_trailers', ['role', 'address_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_trailers_role_addr', table_name='article_trailers')
    op.drop_index(op.f('ix_article_trailers_article_id'), table_name='article_trailers')
    op.drop_table('article_trailers')
    # ### end Alembic commands ###
