"""article patch_series_key + patch_series_version

Revision ID: cfd9b25150b2
Revises: ae03d25e7347
Create Date: 2026-05-14 14:48:56.881564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd9b25150b2'
down_revision: Union[str, Sequence[str], None] = 'ae03d25e7347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('patch_series_key', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('patch_series_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_articles_patch_series_key'), 'articles', ['patch_series_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_patch_series_key'), table_name='articles')
    op.drop_column('articles', 'patch_series_version')
    op.drop_column('articles', 'patch_series_key')
    # ### end Alembic commands ###
