"""add subject_normalized column

Revision ID: d62891242107
Revises: 220d07a097d8
Create Date: 2026-05-03 15:43:35.327603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62891242107'
down_revision: Union[str, Sequence[str], None] = '220d07a097d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'articles',
        sa.Column('subject_normalized', sa.String(), nullable=False, server_default=''),
    )
    op.create_index(op.f('ix_articles_subject_normalized'), 'articles', ['subject_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_subject_normalized'), table_name='articles')
    op.drop_column('articles', 'subject_normalized')
    # ### end Alembic commands ###
