"""add parse_failures table

Revision ID: e1fa8344d719
Revises: c490423609ae
Create Date: 2026-05-05 21:19:51.465617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fa8344d719'
down_revision: Union[str, Sequence[str], None] = 'c490423609ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_failures',
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('error_class', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inbox_id', 'epoch', 'commit_sha')
    )
    op.create_index(op.f('ix_parse_failures_error_class'), 'parse_failures', ['error_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parse_failures_error_class'), table_name='parse_failures')
    op.drop_table('parse_failures')
    # ### end Alembic commands ###
